"""
JAYA Dynamic Feature: Dashboard
Generated by FeatureCompiler v0.1
Feature ID: ee729174
Description: Main dashboard with metrics and quick actions

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "dashboard"
FEATURE_ID = "ee729174"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Main dashboard with metrics and quick actions"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from jaya_core.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from jaya_core.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_ee729174() -> WidgetBase:
    """Build the "Dashboard" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="11954ef4-9611-449a-bf2d-1205993f7fb2",
        label="Untitled",
        layout="flex_col",
        rect={"x": {"value": 0, "unit": "px"}, "y": {"value": 0, "unit": "px"}, "width": {"value": 1200.0, "unit": "px"}, "height": {"value": 800.0, "unit": "px"}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: 12df8bbd
    w_12df8bbd = PanelWidget(
        widget_id="12df8bbd-3728-4044-b590-4b12467f58b9",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    root.add_child(w_12df8bbd)
    # Children of w_12df8bbd
    # label: Untitled
    w_9393c2c7 = LabelWidget(
        widget_id="9393c2c7-0711-4554-805c-40b25377df06",
        label="Untitled",
        visible=True,
        enabled=True,
    )
    w_12df8bbd.add_child(w_9393c2c7)
    # panel: 171207db
    w_171207db = PanelWidget(
        widget_id="171207db-ab0e-4c44-961e-8eede463c4d6",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_12df8bbd.add_child(w_171207db)
    # Children of w_171207db
    # button: New Task
    w_c853f7a8 = ButtonWidget(
        widget_id="c853f7a8-9486-4c07-8008-d00039205fc5",
        label="New Task",
        visible=True,
        enabled=True,
        metadata={"variant": "primary"},
    )
    w_171207db.add_child(w_c853f7a8)
    # Event handlers for w_c853f7a8
    w_c853f7a8.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))
    # button: Settings
    w_080bcbf7 = ButtonWidget(
        widget_id="080bcbf7-322d-4a62-b37b-75cff7e97f39",
        label="Settings",
        visible=True,
        enabled=True,
        metadata={"variant": "secondary"},
    )
    w_171207db.add_child(w_080bcbf7)
    # Event handlers for w_080bcbf7
    w_080bcbf7.on("click", lambda d, a="jaya:open_dialog", p={}: jaya_dispatch(a, p))
    # panel: 540e5bee
    w_540e5bee = PanelWidget(
        widget_id="540e5bee-843d-464b-a897-54300868aca3",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_540e5bee)
    # Children of w_540e5bee
    # panel: ca986313
    w_ca986313 = PanelWidget(
        widget_id="ca986313-4941-4559-bd43-c25388e3cdd0",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_540e5bee.add_child(w_ca986313)
    # Children of w_ca986313
    # panel: 0e3d5819
    w_0e3d5819 = PanelWidget(
        widget_id="0e3d5819-2f44-4335-a19e-01a6fa091776",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_ca986313.add_child(w_0e3d5819)
    # Children of w_0e3d5819
    # label: Total Tasks
    w_da272e2f = LabelWidget(
        widget_id="da272e2f-f2c9-4260-af35-c74604925255",
        label="Total Tasks",
        visible=True,
        enabled=True,
    )
    w_0e3d5819.add_child(w_da272e2f)
    # label: 1,234
    w_ab39d21a = LabelWidget(
        widget_id="ab39d21a-5fa4-41fd-8688-c0577c1b27df",
        label="1,234",
        visible=True,
        enabled=True,
    )
    w_0e3d5819.add_child(w_ab39d21a)
    # label: +12%
    w_54d6964a = LabelWidget(
        widget_id="54d6964a-1421-4798-ad00-e745a43e85a2",
        label="+12%",
        visible=True,
        enabled=True,
    )
    w_0e3d5819.add_child(w_54d6964a)
    # panel: 8e9d94a2
    w_8e9d94a2 = PanelWidget(
        widget_id="8e9d94a2-904b-41c4-8aa3-71a81878cfd2",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_ca986313.add_child(w_8e9d94a2)
    # Children of w_8e9d94a2
    # label: Completed
    w_1f141cda = LabelWidget(
        widget_id="1f141cda-a7d1-493e-9579-3caa0cbac7a0",
        label="Completed",
        visible=True,
        enabled=True,
    )
    w_8e9d94a2.add_child(w_1f141cda)
    # label: 987
    w_129afa0e = LabelWidget(
        widget_id="129afa0e-a712-41eb-a6cf-e6116957437a",
        label="987",
        visible=True,
        enabled=True,
    )
    w_8e9d94a2.add_child(w_129afa0e)
    # label: +8%
    w_4938d7b9 = LabelWidget(
        widget_id="4938d7b9-e9c5-4030-b4e4-c79f2109538e",
        label="+8%",
        visible=True,
        enabled=True,
    )
    w_8e9d94a2.add_child(w_4938d7b9)
    # panel: 3ebf9a19
    w_3ebf9a19 = PanelWidget(
        widget_id="3ebf9a19-7a6e-45ab-8110-da77b46c38ca",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_ca986313.add_child(w_3ebf9a19)
    # Children of w_3ebf9a19
    # label: In Progress
    w_6904d0d8 = LabelWidget(
        widget_id="6904d0d8-fc6e-4575-919f-2e4fd202f98c",
        label="In Progress",
        visible=True,
        enabled=True,
    )
    w_3ebf9a19.add_child(w_6904d0d8)
    # label: 156
    w_6cb67f5d = LabelWidget(
        widget_id="6cb67f5d-3f15-4bdf-9546-496197acb1dc",
        label="156",
        visible=True,
        enabled=True,
    )
    w_3ebf9a19.add_child(w_6cb67f5d)
    # label: -3%
    w_7a789a50 = LabelWidget(
        widget_id="7a789a50-077d-4135-b7a9-445a515fade5",
        label="-3%",
        visible=True,
        enabled=True,
    )
    w_3ebf9a19.add_child(w_7a789a50)
    # panel: c8974f42
    w_c8974f42 = PanelWidget(
        widget_id="c8974f42-8239-4489-9f77-aafe62cca697",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_ca986313.add_child(w_c8974f42)
    # Children of w_c8974f42
    # label: Overdue
    w_2694b6b2 = LabelWidget(
        widget_id="2694b6b2-9356-445d-b3d7-6914b6f97e53",
        label="Overdue",
        visible=True,
        enabled=True,
    )
    w_c8974f42.add_child(w_2694b6b2)
    # label: 12
    w_1cc1dc3c = LabelWidget(
        widget_id="1cc1dc3c-b84d-4a40-b69e-e45472fc5384",
        label="12",
        visible=True,
        enabled=True,
    )
    w_c8974f42.add_child(w_1cc1dc3c)
    # label: +2%
    w_99ba2751 = LabelWidget(
        widget_id="99ba2751-2d65-46f8-99dd-560dafc3c105",
        label="+2%",
        visible=True,
        enabled=True,
    )
    w_c8974f42.add_child(w_99ba2751)

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.

    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict

    Returns:
        Result dict with status and any output data
    """
    config = config or {}

    # Build scene
    root = build_scene_ee729174()

    # Initialize runtime
    from jaya_core.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="ee729174",
        feature_name="dashboard",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )

    # Set global runtime reference for dispatch
    set_runtime(runtime)

    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))

    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "dashboard"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.

    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action

    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}

    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        print(f"Warning: No JAYA bridge set, action {action} dropped")
        return None

    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as e:
        print(f"JAYA dispatch error: {e}")
        return None

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
