"""Pillar 36 — Speculative Reasoning (Foresight).

When the engine's confidence falls below ``AgiConfig.uncertainty_threshold``
the SpeculativeEngine fans out N parallel mini-experiments via the twin,
collects their scores, and returns the best result.  This "foresight loop"
lets JAYA speculatively pre-compute multiple answer paths and pick the
most promising one instead of committing blindly.

Architecture
------------
    IronEngine                       SpeculativeEngine
        │                                  │
        │  confidence < threshold          │
        ├─────────────────────────────────>│
        │                                  │─── asyncio.gather(N tasks)
        │                                  │         │
        │                                  │  CoreTwin.run_experiment() × N
        │                                  │         │
        │               best_result  ──────┤<────────┘
        │<─────────────────────────────────┤
"""

import asyncio
import logging
from typing import Any, Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from src.brain_v2.extensions.twin.core_twin import CoreTwin

logger = logging.getLogger("Speculative")


class SpeculativeEngine:
    """Fan-out speculative reasoning via parallel twin experiments.

    Parameters
    ----------
    n_paths:
        Number of parallel speculation paths to evaluate.
    timeout:
        Max seconds to wait for all speculative paths to complete.
    """

    def __init__(self, n_paths: int = 3, timeout: float = 5.0):
        self.n_paths  = n_paths
        self.timeout  = timeout
        self._runs: int    = 0
        self._wins: int    = 0

    # ------------------------------------------------------------------

    async def speculate(self,
                        twin: "CoreTwin",
                        base_code: str,
                        variants: Optional[List[str]] = None) -> Dict[str, Any]:
        """Run *n_paths* speculative variants and return the best outcome.

        Parameters
        ----------
        twin:
            The CoreTwin instance providing isolated exec().
        base_code:
            The primary code to evaluate.
        variants:
            Optional list of alternative code variants.  If fewer than
            ``n_paths`` variants are provided (or None), padding variants
            are auto-generated by tweaking parameter literals.
        """
        paths = self._build_paths(base_code, variants)
        self._runs += 1

        logger.info("[Speculative run #%d] %d paths | base code len=%d",
                    self._runs, len(paths), len(base_code))

        # Run all paths concurrently with a timeout
        tasks = [
            asyncio.create_task(
                twin.run_experiment(code, label="SPECULATE")
            )
            for code in paths
        ]

        done, pending = await asyncio.wait(
            tasks, timeout=self.timeout,
            return_when=asyncio.ALL_COMPLETED,
        )
        for t in pending:
            t.cancel()

        # Collect results from completed tasks
        results: List[Dict[str, Any]] = []
        for task in done:
            try:
                results.append(task.result())
            except Exception:
                pass

        if not results:
            logger.warning("[Speculative] all paths timed out or failed")
            return {"__error__": "all_paths_failed", "score": 0.0}

        # Pick the highest-scoring result
        best = max(results,
                   key=lambda r: float(r.get("score") or r.get("fitness") or 0.0))

        best_score = float(best.get("score") or 0.0)
        logger.info("[Speculative] best score=%.3f from %d completed paths",
                    best_score, len(results))

        if best_score > 0:
            self._wins += 1

        return best

    # ------------------------------------------------------------------

    def _build_paths(self,
                     base_code: str,
                     variants: Optional[List[str]]) -> List[str]:
        """Return a list of *n_paths* code strings to try."""
        paths: List[str] = [base_code]
        if variants:
            paths.extend(variants[: self.n_paths - 1])

        # Auto-pad with simple perturbations of the base
        import re
        while len(paths) < self.n_paths:
            perturbed = re.sub(
                r"\b(\d+\.?\d*)\b",
                lambda m: str(round(float(m.group(1)) * (1 + 0.1 * len(paths)), 4)),
                base_code,
            )
            if perturbed == paths[-1]:
                break  # can't perturb further
            paths.append(perturbed)

        return paths[: self.n_paths]

    # ------------------------------------------------------------------

    def status(self) -> Dict[str, Any]:
        return {
            "available": True,
            "n_paths":  self.n_paths,
            "timeout":  self.timeout,
            "runs":     self._runs,
            "wins":     self._wins,
        }
