"""
JAYA Dynamic Feature: Dashboard
Generated by FeatureCompiler v0.1
Feature ID: e2e39936
Description: Main dashboard with metrics and quick actions

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "dashboard"
FEATURE_ID = "e2e39936"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Main dashboard with metrics and quick actions"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from src.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from src.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_e2e39936() -> WidgetBase:
    """Build the "Dashboard" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="10f2f677-bc50-4198-92cc-4b67d3e073b4",
        label="Untitled",
        layout="flex_col",
        rect={"x": {"value": 0, "unit": "px"}, "y": {"value": 0, "unit": "px"}, "width": {"value": 1200.0, "unit": "px"}, "height": {"value": 800.0, "unit": "px"}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: cdc06f8b
    w_cdc06f8b = PanelWidget(
        widget_id="cdc06f8b-48a0-46a3-a4f8-94c5cd052c80",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    root.add_child(w_cdc06f8b)
    # Children of w_cdc06f8b
    # label: Untitled
    w_448d334c = LabelWidget(
        widget_id="448d334c-1764-4331-bbc3-c437e92a7bd4",
        label="Untitled",
        visible=True,
        enabled=True,
    )
    w_cdc06f8b.add_child(w_448d334c)
    # panel: 7d449ae2
    w_7d449ae2 = PanelWidget(
        widget_id="7d449ae2-af8e-4fae-875d-6befda102c75",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_cdc06f8b.add_child(w_7d449ae2)
    # Children of w_7d449ae2
    # button: New Task
    w_9b99e2e8 = ButtonWidget(
        widget_id="9b99e2e8-9ff9-43a1-a23c-ba4b14766094",
        label="New Task",
        visible=True,
        enabled=True,
        metadata={"variant": "primary"},
    )
    w_7d449ae2.add_child(w_9b99e2e8)
    # Event handlers for w_9b99e2e8
    w_9b99e2e8.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))
    # button: Settings
    w_3c218892 = ButtonWidget(
        widget_id="3c218892-4e2b-479c-98f9-5d52d70fe2b4",
        label="Settings",
        visible=True,
        enabled=True,
        metadata={"variant": "secondary"},
    )
    w_7d449ae2.add_child(w_3c218892)
    # Event handlers for w_3c218892
    w_3c218892.on("click", lambda d, a="jaya:open_dialog", p={}: jaya_dispatch(a, p))
    # panel: 65aa5642
    w_65aa5642 = PanelWidget(
        widget_id="65aa5642-5a9a-4307-9325-c2cbe303d0b5",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_65aa5642)
    # Children of w_65aa5642
    # panel: edbf6107
    w_edbf6107 = PanelWidget(
        widget_id="edbf6107-bdaf-4097-8813-17910f2b9363",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_65aa5642.add_child(w_edbf6107)
    # Children of w_edbf6107
    # panel: e0237921
    w_e0237921 = PanelWidget(
        widget_id="e0237921-6eda-48db-87c9-1d8fe24f582c",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_edbf6107.add_child(w_e0237921)
    # Children of w_e0237921
    # label: Total Tasks
    w_09bf3c53 = LabelWidget(
        widget_id="09bf3c53-294b-423f-b90d-36a529faa9dc",
        label="Total Tasks",
        visible=True,
        enabled=True,
    )
    w_e0237921.add_child(w_09bf3c53)
    # label: 1,234
    w_f26bb0be = LabelWidget(
        widget_id="f26bb0be-5e2a-4ca1-aa89-8b85c2b85167",
        label="1,234",
        visible=True,
        enabled=True,
    )
    w_e0237921.add_child(w_f26bb0be)
    # label: +12%
    w_164c1356 = LabelWidget(
        widget_id="164c1356-d8a8-48c4-b13b-23df02e60d01",
        label="+12%",
        visible=True,
        enabled=True,
    )
    w_e0237921.add_child(w_164c1356)
    # panel: c300d9ce
    w_c300d9ce = PanelWidget(
        widget_id="c300d9ce-f450-4bea-aed5-4ccdb4cc87eb",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_edbf6107.add_child(w_c300d9ce)
    # Children of w_c300d9ce
    # label: Completed
    w_53738e35 = LabelWidget(
        widget_id="53738e35-d519-46bf-bf03-3992ecf6558a",
        label="Completed",
        visible=True,
        enabled=True,
    )
    w_c300d9ce.add_child(w_53738e35)
    # label: 987
    w_4c331b18 = LabelWidget(
        widget_id="4c331b18-6375-4271-a3b4-9b9de24db2a8",
        label="987",
        visible=True,
        enabled=True,
    )
    w_c300d9ce.add_child(w_4c331b18)
    # label: +8%
    w_458fe4b2 = LabelWidget(
        widget_id="458fe4b2-10b3-405d-a844-05272c4a6844",
        label="+8%",
        visible=True,
        enabled=True,
    )
    w_c300d9ce.add_child(w_458fe4b2)
    # panel: a238aefc
    w_a238aefc = PanelWidget(
        widget_id="a238aefc-0b74-4537-90fe-d969bef4139f",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_edbf6107.add_child(w_a238aefc)
    # Children of w_a238aefc
    # label: In Progress
    w_ce7cebc3 = LabelWidget(
        widget_id="ce7cebc3-9c2d-4cc0-876a-e5b7c5b5af11",
        label="In Progress",
        visible=True,
        enabled=True,
    )
    w_a238aefc.add_child(w_ce7cebc3)
    # label: 156
    w_329034c5 = LabelWidget(
        widget_id="329034c5-ba96-4750-b8f6-2e2e237ee951",
        label="156",
        visible=True,
        enabled=True,
    )
    w_a238aefc.add_child(w_329034c5)
    # label: -3%
    w_9d4a9cb8 = LabelWidget(
        widget_id="9d4a9cb8-0086-4c40-8cf6-9955cbcabe0f",
        label="-3%",
        visible=True,
        enabled=True,
    )
    w_a238aefc.add_child(w_9d4a9cb8)
    # panel: 7453a99f
    w_7453a99f = PanelWidget(
        widget_id="7453a99f-49e3-4e3f-b54e-9004a5067fad",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_edbf6107.add_child(w_7453a99f)
    # Children of w_7453a99f
    # label: Overdue
    w_94fc6e80 = LabelWidget(
        widget_id="94fc6e80-c3a5-4502-ada9-aa0b5336e054",
        label="Overdue",
        visible=True,
        enabled=True,
    )
    w_7453a99f.add_child(w_94fc6e80)
    # label: 12
    w_1faaa305 = LabelWidget(
        widget_id="1faaa305-6c7d-416e-a51c-2865388e8d27",
        label="12",
        visible=True,
        enabled=True,
    )
    w_7453a99f.add_child(w_1faaa305)
    # label: +2%
    w_64ced3d6 = LabelWidget(
        widget_id="64ced3d6-211e-40b4-8ebd-d7699a100345",
        label="+2%",
        visible=True,
        enabled=True,
    )
    w_7453a99f.add_child(w_64ced3d6)

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.

    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict

    Returns:
        Result dict with status and any output data
    """
    config = config or {}

    # Build scene
    root = build_scene_e2e39936()

    # Initialize runtime
    from src.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="e2e39936",
        feature_name="dashboard",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )

    # Set global runtime reference for dispatch
    set_runtime(runtime)

    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))

    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "dashboard"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.

    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action

    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}

    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        print(f"Warning: No JAYA bridge set, action {action} dropped")
        return None

    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as e:
        print(f"JAYA dispatch error: {e}")
        return None

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
