"""
JAYA Dynamic Feature: Dashboard
Generated by FeatureCompiler v0.1
Feature ID: ebd1ea75-aeed-4cd0-b537-1d29946be862
Description: Main dashboard with metrics and quick actions

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "dashboard"
FEATURE_ID = "ebd1ea75-aeed-4cd0-b537-1d29946be862"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Main dashboard with metrics and quick actions"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from src.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from src.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_ebd1ea75() -> WidgetBase:
    """Build the "Dashboard" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="d83abff9-9d91-4d3c-8ab5-e87028f621d1",
        label="Untitled",
        layout="flex_col",
        rect={'x': {'value': 0, 'unit': <SizeUnit.PX: 'px'>}, 'y': {'value': 0, 'unit': <SizeUnit.PX: 'px'>}, 'width': {'value': 1200.0, 'unit': <SizeUnit.PX: 'px'>}, 'height': {'value': 800.0, 'unit': <SizeUnit.PX: 'px'>}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: 8643a3c9
    w_8643a3c9 = PanelWidget(
        widget_id="8643a3c9-9f5b-4e46-8205-d28351a646a7",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    root.add_child(w_8643a3c9)
    # Children of w_8643a3c9
    # label: Untitled
    w_2d6be9dc = LabelWidget(
        widget_id="2d6be9dc-b925-4b32-bf29-849b4b81dba5",
        label="Untitled",
        visible=True,
        enabled=True,
    )
    w_8643a3c9.add_child(w_2d6be9dc)
    # panel: 0b20208e
    w_0b20208e = PanelWidget(
        widget_id="0b20208e-a89b-4e28-be7c-014806a47675",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_8643a3c9.add_child(w_0b20208e)
    # Children of w_0b20208e
    # button: New Task
    w_e423380d = ButtonWidget(
        widget_id="e423380d-c81d-4249-aa4b-c7a93e4997a8",
        label="New Task",
        visible=True,
        enabled=True,
        metadata={'variant': 'primary'},
    )
    w_0b20208e.add_child(w_e423380d)
    # Event handlers for w_e423380d
    w_e423380d.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))
    # button: Settings
    w_4d1a0ea6 = ButtonWidget(
        widget_id="4d1a0ea6-beb7-4e92-89bf-f1dc197b9794",
        label="Settings",
        visible=True,
        enabled=True,
        metadata={'variant': 'secondary'},
    )
    w_0b20208e.add_child(w_4d1a0ea6)
    # Event handlers for w_4d1a0ea6
    w_4d1a0ea6.on("click", lambda d, a="jaya:open_dialog", p={}: jaya_dispatch(a, p))
    # panel: e39e6d64
    w_e39e6d64 = PanelWidget(
        widget_id="e39e6d64-f470-4516-812e-d365f88ef0e3",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_e39e6d64)
    # Children of w_e39e6d64
    # panel: 3138afeb
    w_3138afeb = PanelWidget(
        widget_id="3138afeb-6437-4d52-a144-a24798641175",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_e39e6d64.add_child(w_3138afeb)
    # Children of w_3138afeb
    # panel: 6c2fa802
    w_6c2fa802 = PanelWidget(
        widget_id="6c2fa802-3d6a-456e-90d6-55e04327826a",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_3138afeb.add_child(w_6c2fa802)
    # Children of w_6c2fa802
    # label: Total Tasks
    w_99ab0525 = LabelWidget(
        widget_id="99ab0525-ff30-49a5-b0b2-03828a55f746",
        label="Total Tasks",
        visible=True,
        enabled=True,
    )
    w_6c2fa802.add_child(w_99ab0525)
    # label: 1,234
    w_68dbb844 = LabelWidget(
        widget_id="68dbb844-09e3-4a20-8425-a823277dcf6d",
        label="1,234",
        visible=True,
        enabled=True,
    )
    w_6c2fa802.add_child(w_68dbb844)
    # label: +12%
    w_8410da2b = LabelWidget(
        widget_id="8410da2b-70a0-4c62-9ee0-52b7de42d2cc",
        label="+12%",
        visible=True,
        enabled=True,
    )
    w_6c2fa802.add_child(w_8410da2b)
    # panel: 051b7fe3
    w_051b7fe3 = PanelWidget(
        widget_id="051b7fe3-f62b-4584-8f92-991cdcf6c4a2",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_3138afeb.add_child(w_051b7fe3)
    # Children of w_051b7fe3
    # label: Completed
    w_b4fbbaae = LabelWidget(
        widget_id="b4fbbaae-2aa8-4e9d-b3f3-03118da050f2",
        label="Completed",
        visible=True,
        enabled=True,
    )
    w_051b7fe3.add_child(w_b4fbbaae)
    # label: 987
    w_cc95a90e = LabelWidget(
        widget_id="cc95a90e-5847-4fd1-b3c8-88d68f49f5dc",
        label="987",
        visible=True,
        enabled=True,
    )
    w_051b7fe3.add_child(w_cc95a90e)
    # label: +8%
    w_7f5b4a11 = LabelWidget(
        widget_id="7f5b4a11-ad09-46c1-8100-b3ed2c534769",
        label="+8%",
        visible=True,
        enabled=True,
    )
    w_051b7fe3.add_child(w_7f5b4a11)
    # panel: f93578de
    w_f93578de = PanelWidget(
        widget_id="f93578de-e684-49ff-ad7d-2c175b86f974",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_3138afeb.add_child(w_f93578de)
    # Children of w_f93578de
    # label: In Progress
    w_3353cffd = LabelWidget(
        widget_id="3353cffd-0fdf-4290-8b13-41d1ce5fa4ab",
        label="In Progress",
        visible=True,
        enabled=True,
    )
    w_f93578de.add_child(w_3353cffd)
    # label: 156
    w_84e978ed = LabelWidget(
        widget_id="84e978ed-6f42-4660-9747-71a2c8765229",
        label="156",
        visible=True,
        enabled=True,
    )
    w_f93578de.add_child(w_84e978ed)
    # label: -3%
    w_bd9f972c = LabelWidget(
        widget_id="bd9f972c-23ca-4b39-bc54-b9b80a1d342b",
        label="-3%",
        visible=True,
        enabled=True,
    )
    w_f93578de.add_child(w_bd9f972c)
    # panel: 4f2f20be
    w_4f2f20be = PanelWidget(
        widget_id="4f2f20be-e5d3-4626-ac0f-8f5bc28e6140",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_3138afeb.add_child(w_4f2f20be)
    # Children of w_4f2f20be
    # label: Overdue
    w_5d719a76 = LabelWidget(
        widget_id="5d719a76-8e3e-4723-b27a-fe54b35ed3a9",
        label="Overdue",
        visible=True,
        enabled=True,
    )
    w_4f2f20be.add_child(w_5d719a76)
    # label: 12
    w_b9de67d2 = LabelWidget(
        widget_id="b9de67d2-55a7-4407-b66b-f2ba62c90bcd",
        label="12",
        visible=True,
        enabled=True,
    )
    w_4f2f20be.add_child(w_b9de67d2)
    # label: +2%
    w_22141f36 = LabelWidget(
        widget_id="22141f36-a932-4bb3-a9ab-69e832a0db0d",
        label="+2%",
        visible=True,
        enabled=True,
    )
    w_4f2f20be.add_child(w_22141f36)

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.

    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict

    Returns:
        Result dict with status and any output data
    """
    config = config or {}

    # Build scene
    root = build_scene_ebd1ea75()

    # Initialize runtime
    from src.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="ebd1ea75-aeed-4cd0-b537-1d29946be862",
        feature_name="dashboard",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )

    # Set global runtime reference for dispatch
    set_runtime(runtime)

    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))

    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "dashboard"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

def feature_manifest() -> Dict[str, Any]:
    """Return the generated feature's registration contract."""
    return {
        "name": FEATURE_NAME,
        "id": FEATURE_ID,
        "version": FEATURE_VERSION,
        "description": FEATURE_DESCRIPTION,
        "protocol_version": FEATURE_PROTOCOL_VERSION,
        "entry_point": "run_feature",
        "capabilities": ["ui", "events", "state", "jaya_actions"],
        "permissions": ["ui_mount", "state_read", "state_write", "api_call"],
    }

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.

    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action

    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}

    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        return {
            "success": False,
            "error_code": "BRIDGE_UNAVAILABLE",
            "action": action,
        }

    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as exc:
        return {
            "success": False,
            "error_code": "BRIDGE_DISPATCH_FAILED",
            "action": action,
            "error_type": type(exc).__name__,
        }

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
