"""
JAYA Dynamic Feature: Feature: {
  "version": "0.1",
  "id": "aa983f44-28b0-452f-
Generated by FeatureCompiler v0.1
Feature ID: a5c70b8d
Description: Auto-generated feature for: {
  "version": "0.1",
  "id": "aa983f44-28b0-452f-88ac-32cf4bed1618",
  "name": "Test Dialog",
  "description": "Test dialog",
  "root": {
    "id": "caa749c4-e4cc-4e07-bcaa-8d0c4d655e8a",
    "type": "window",
    "label": "Test",
    "placeholder": "",
    "value": null,
    "options": [],
    "children": [
      {
        "id": "44595e29-de4e-49d2-ab7a-f2e8565bee5f",
        "type": "panel",
        "label": "",
        "placeholder": "",
        "value": null,
        "options": [],
        "children": [
          {
            "id": "9601a0ed-f4e0-43a5-9dc6-6ccd3f523340",
            "type": "label",
            "label": "Hello World",
            "placeholder": "",
            "value": null,
            "options": [],
            "children": [],
            "style": {},
            "layout": null,
            "rect": null,
            "events": [],
            "bindings": [],
            "visible": true,
            "enabled": true,
            "metadata": {}
          }
        ],
        "style": {},
        "layout": "flex_col",
        "rect": null,
        "events": [],
        "bindings": [],
        "visible": true,
        "enabled": true,
        "metadata": {}
      }
    ],
    "style": {},
    "layout": "flex_col",
    "rect": {
      "x": {
        "value": 0,
        "unit": "px"
      },
      "y": {
        "value": 0,
        "unit": "px"
      },
      "width": {
        "value": 300.0,
        "unit": "px"
      },
      "height": {
        "value": 200.0,
        "unit": "px"
      }
    },
    "events": [],
    "bindings": [],
    "visible": true,
    "enabled": true,
    "metadata": {}
  },
  "styles": {
    "color_primary": "#0066CC",
    "color_secondary": "#6C757D",
    "color_success": "#28A745",
    "color_warning": "#FFC107",
    "color_danger": "#DC3545",
    "color_background": "#FFFFFF",
    "color_surface": "#F8F9FA",
    "color_text": "#212529",
    "color_text_muted": "#6C757D",
    "color_border": "#DEE2E6",
    "spacing_xs": "4px",
    "spacing_sm": "8px",
    "spacing_md": "16px",
    "spacing_lg": "24px",
    "spacing_xl": "32px",
    "font_family": "system-ui, -apple-system, sans-serif",
    "font_size_sm": "12px",
    "font_size_md": "14px",
    "font_size_lg": "18px",
    "font_size_xl": "24px",
    "font_weight_normal": 400,
    "font_weight_medium": 500,
    "font_weight_bold": 700,
    "border_radius_sm": "4px",
    "border_radius_md": "8px",
    "border_radius_lg": "12px",
    "border_width": "1px",
    "shadow_sm": "0 1px 2px rgba(0,0,0,0.05)",
    "shadow_md": "0 4px 6px rgba(0,0,0,0.1)",
    "shadow_lg": "0 10px 15px rgba(0,0,0,0.1)",
    "transition_fast": "150ms ease",
    "transition_normal": "250ms ease",
    "transition_slow": "350ms ease"
  },
  "global_state": {},
  "metadata": {}
}

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "test_dialog"
FEATURE_ID = "a5c70b8d"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Auto-generated feature for: {
  "version": "0.1",
  "id": "aa983f44-28b0-452f-88ac-32cf4bed1618",
  "name": "Test Dialog",
  "description": "Test dialog",
  "root": {
    "id": "caa749c4-e4cc-4e07-bcaa-8d0c4d655e8a",
    "type": "window",
    "label": "Test",
    "placeholder": "",
    "value": null,
    "options": [],
    "children": [
      {
        "id": "44595e29-de4e-49d2-ab7a-f2e8565bee5f",
        "type": "panel",
        "label": "",
        "placeholder": "",
        "value": null,
        "options": [],
        "children": [
          {
            "id": "9601a0ed-f4e0-43a5-9dc6-6ccd3f523340",
            "type": "label",
            "label": "Hello World",
            "placeholder": "",
            "value": null,
            "options": [],
            "children": [],
            "style": {},
            "layout": null,
            "rect": null,
            "events": [],
            "bindings": [],
            "visible": true,
            "enabled": true,
            "metadata": {}
          }
        ],
        "style": {},
        "layout": "flex_col",
        "rect": null,
        "events": [],
        "bindings": [],
        "visible": true,
        "enabled": true,
        "metadata": {}
      }
    ],
    "style": {},
    "layout": "flex_col",
    "rect": {
      "x": {
        "value": 0,
        "unit": "px"
      },
      "y": {
        "value": 0,
        "unit": "px"
      },
      "width": {
        "value": 300.0,
        "unit": "px"
      },
      "height": {
        "value": 200.0,
        "unit": "px"
      }
    },
    "events": [],
    "bindings": [],
    "visible": true,
    "enabled": true,
    "metadata": {}
  },
  "styles": {
    "color_primary": "#0066CC",
    "color_secondary": "#6C757D",
    "color_success": "#28A745",
    "color_warning": "#FFC107",
    "color_danger": "#DC3545",
    "color_background": "#FFFFFF",
    "color_surface": "#F8F9FA",
    "color_text": "#212529",
    "color_text_muted": "#6C757D",
    "color_border": "#DEE2E6",
    "spacing_xs": "4px",
    "spacing_sm": "8px",
    "spacing_md": "16px",
    "spacing_lg": "24px",
    "spacing_xl": "32px",
    "font_family": "system-ui, -apple-system, sans-serif",
    "font_size_sm": "12px",
    "font_size_md": "14px",
    "font_size_lg": "18px",
    "font_size_xl": "24px",
    "font_weight_normal": 400,
    "font_weight_medium": 500,
    "font_weight_bold": 700,
    "border_radius_sm": "4px",
    "border_radius_md": "8px",
    "border_radius_lg": "12px",
    "border_width": "1px",
    "shadow_sm": "0 1px 2px rgba(0,0,0,0.05)",
    "shadow_md": "0 4px 6px rgba(0,0,0,0.1)",
    "shadow_lg": "0 10px 15px rgba(0,0,0,0.1)",
    "transition_fast": "150ms ease",
    "transition_normal": "250ms ease",
    "transition_slow": "350ms ease"
  },
  "global_state": {},
  "metadata": {}
}"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from src.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from src.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_a5c70b8d() -> WidgetBase:
    """Build the "Feature: {
  "version": "0.1",
  "id": "aa983f44-28b0-452f-" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="2b0dd559-8f79-4243-91ec-66df007d5d5e",
        label="""JAYA Feature: {
  "version": "0.1",
  "id": "aa983f44-"
}""",
        layout="flex_col",
        rect={"x": {"value": 0, "unit": "px"}, "y": {"value": 0, "unit": "px"}, "width": {"value": 600.0, "unit": "px"}, "height": {"value": 400.0, "unit": "px"}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: 0dabd7d1
    w_0dabd7d1 = PanelWidget(
        widget_id="0dabd7d1-58dc-4f3a-9adf-ef0875300f02",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_0dabd7d1)
    # Children of w_0dabd7d1
    """Original generated label metadata: Feature for: {
  "version": "0.1",
  "id": "aa983f44-28b0-452f-88ac-32cf4bed1618",
  "name": "Test Dialog",
  "description": "Test dialog",
  "root": {
    "id": "caa749c4-e4cc-4e07-bcaa-8d0c4d655e8a",
    "type": "window",
    "label": "Test",
    "placeholder": "",
    "value": null,
    "options": [],
    "children": [
      {
        "id": "44595e29-de4e-49d2-ab7a-f2e8565bee5f",
        "type": "panel",
        "label": "",
        "placeholder": "",
        "value": null,
        "options": [],
        "children": [
          {
            "id": "9601a0ed-f4e0-43a5-9dc6-6ccd3f523340",
            "type": "label",
            "label": "Hello World",
            "placeholder": "",
            "value": null,
            "options": [],
            "children": [],
            "style": {},
            "layout": null,
            "rect": null,
            "events": [],
            "bindings": [],
            "visible": true,
            "enabled": true,
            "metadata": {}
          }
        ],
        "style": {},
        "layout": "flex_col",
        "rect": null,
        "events": [],
        "bindings": [],
        "visible": true,
        "enabled": true,
        "metadata": {}
      }
    ],
    "style": {},
    "layout": "flex_col",
    "rect": {
      "x": {
        "value": 0,
        "unit": "px"
      },
      "y": {
        "value": 0,
        "unit": "px"
      },
      "width": {
        "value": 300.0,
        "unit": "px"
      },
      "height": {
        "value": 200.0,
        "unit": "px"
      }
    },
    "events": [],
    "bindings": [],
    "visible": true,
    "enabled": true,
    "metadata": {}
  },
  "styles": {
    "color_primary": "#0066CC",
    "color_secondary": "#6C757D",
    "color_success": "#28A745",
    "color_warning": "#FFC107",
    "color_danger": "#DC3545",
    "color_background": "#FFFFFF",
    "color_surface": "#F8F9FA",
    "color_text": "#212529",
    "color_text_muted": "#6C757D",
    "color_border": "#DEE2E6",
    "spacing_xs": "4px",
    "spacing_sm": "8px",
    "spacing_md": "16px",
    "spacing_lg": "24px",
    "spacing_xl": "32px",
    "font_family": "system-ui, -apple-system, sans-serif",
    "font_size_sm": "12px",
    "font_size_md": "14px",
    "font_size_lg": "18px",
    "font_size_xl": "24px",
    "font_weight_normal": 400,
    "font_weight_medium": 500,
    "font_weight_bold": 700,
    "border_radius_sm": "4px",
    "border_radius_md": "8px",
    "border_radius_lg": "12px",
    "border_width": "1px",
    "shadow_sm": "0 1px 2px rgba(0,0,0,0.05)",
    "shadow_md": "0 4px 6px rgba(0,0,0,0.1)",
    "shadow_lg": "0 10px 15px rgba(0,0,0,0.1)",
    "transition_fast": "150ms ease",
    "transition_normal": "250ms ease",
    "transition_slow": "350ms ease"
  },
  "global_state": {},
  "metadata": {}
}"""
    w_cb93af7a = LabelWidget(
        widget_id="cb93af7a-440f-4bdd-8741-f73056f1c337",
        label="""Feature for: {
  "version": "0.1",
  "id": "aa983f44-28b0-452f-88ac-32cf4bed1618",
  "name": "Test Dialog",
  "description": "Test dialog",
  "root": {
    "id": "caa749c4-e4cc-4e07-bcaa-8d0c4d655e8a",
    "type": "window",
    "label": "Test",
    "placeholder": "",
    "value": null,
    "options": [],
    "children": [
      {
        "id": "44595e29-de4e-49d2-ab7a-f2e8565bee5f",
        "type": "panel",
        "label": "",
        "placeholder": "",
        "value": null,
        "options": [],
        "children": [
          {
            "id": "9601a0ed-f4e0-43a5-9dc6-6ccd3f523340",
            "type": "label",
            "label": "Hello World",
            "placeholder": "",
            "value": null,
            "options": [],
            "children": [],
            "style": {},
            "layout": null,
            "rect": null,
            "events": [],
            "bindings": [],
            "visible": true,
            "enabled": true,
            "metadata": {}
          }
        ],
        "style": {},
        "layout": "flex_col",
        "rect": null,
        "events": [],
        "bindings": [],
        "visible": true,
        "enabled": true,
        "metadata": {}
      }
    ],
    "style": {},
    "layout": "flex_col",
    "rect": {
      "x": {
        "value": 0,
        "unit": "px"
      },
      "y": {
        "value": 0,
        "unit": "px"
      },
      "width": {
        "value": 300.0,
        "unit": "px"
      },
      "height": {
        "value": 200.0,
        "unit": "px"
      }
    },
    "events": [],
    "bindings": [],
    "visible": true,
    "enabled": true,
    "metadata": {}
  },
  "styles": {
    "color_primary": "#0066CC",
    "color_secondary": "#6C757D",
    "color_success": "#28A745",
    "color_warning": "#FFC107",
    "color_danger": "#DC3545",
    "color_background": "#FFFFFF",
    "color_surface": "#F8F9FA",
    "color_text": "#212529",
    "color_text_muted": "#6C757D",
    "color_border": "#DEE2E6",
    "spacing_xs": "4px",
    "spacing_sm": "8px",
    "spacing_md": "16px",
    "spacing_lg": "24px",
    "spacing_xl": "32px",
    "font_family": "system-ui, -apple-system, sans-serif",
    "font_size_sm": "12px",
    "font_size_md": "14px",
    "font_size_lg": "18px",
    "font_size_xl": "24px",
    "font_weight_normal": 400,
    "font_weight_medium": 500,
    "font_weight_bold": 700,
    "border_radius_sm": "4px",
    "border_radius_md": "8px",
    "border_radius_lg": "12px",
    "border_width": "1px",
    "shadow_sm": "0 1px 2px rgba(0,0,0,0.05)",
    "shadow_md": "0 4px 6px rgba(0,0,0,0.1)",
    "shadow_lg": "0 10px 15px rgba(0,0,0,0.1)",
    "transition_fast": "150ms ease",
    "transition_normal": "250ms ease",
    "transition_slow": "350ms ease"
  },
  "global_state": {},
  "metadata": {}
}""",
        visible=True,
        enabled=True,
    )
    w_0dabd7d1.add_child(w_cb93af7a)
    # label: This feature was auto-generated from your intent.
    w_9ade3105 = LabelWidget(
        widget_id="9ade3105-38fe-40a1-8635-cb56f9a877fa",
        label="This feature was auto-generated from your intent.",
        visible=True,
        enabled=True,
    )
    w_0dabd7d1.add_child(w_9ade3105)
    # button: Close
    w_1e85fee6 = ButtonWidget(
        widget_id="1e85fee6-e2fd-455a-ad08-db4a1072d991",
        label="Close",
        visible=True,
        enabled=True,
        metadata={"variant": "secondary"},
    )
    w_0dabd7d1.add_child(w_1e85fee6)
    # Event handlers for w_1e85fee6
    w_1e85fee6.on("click", lambda d, a="jaya:close_dialog", p={}: jaya_dispatch(a, p))

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.
    
    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict
        
    Returns:
        Result dict with status and any output data
    """
    config = config or {}
    
    # Initialize runtime
    runtime = FeatureRuntime(jaya_bridge)
    
    # Build scene
    root = build_scene_a5c70b8d()
    
    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))
    
    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "test_dialog"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()


def feature_manifest() -> Dict[str, Any]:
    """Return feature manifest for registration."""
    return {
        "name": FEATURE_NAME,
        "id": FEATURE_ID,
        "version": FEATURE_VERSION,
        "description": FEATURE_DESCRIPTION,
        "protocol_version": FEATURE_PROTOCOL_VERSION,
        "entry_point": "run_feature",
        "capabilities": ["ui", "events", "state", "jaya_actions"],
        "permissions": ["ui_mount", "state_read", "state_write", "api_call"],
    }


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        print(f"Warning: No JAYA bridge set, action {action} dropped")
        return None
    
    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as e:
        print(f"JAYA dispatch error: {e}")
        return None

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
