"""
JAYA Dynamic Feature: Dashboard
Generated by FeatureCompiler v0.1
Feature ID: 99fbade1
Description: Main dashboard with metrics and quick actions

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "dashboard"
FEATURE_ID = "99fbade1-c681-4d1e-8c3e-d48aaf5d502a"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Main dashboard with metrics and quick actions"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from jaya_core.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from jaya_core.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_99fbade1() -> WidgetBase:
    """Build the "Dashboard" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="738b5abf-cbe3-4dd7-850f-34db969b87a8",
        label="Untitled",
        layout="flex_col",
        rect={"x": {"value": 0, "unit": "px"}, "y": {"value": 0, "unit": "px"}, "width": {"value": 1200.0, "unit": "px"}, "height": {"value": 800.0, "unit": "px"}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: 06edd2fd
    w_06edd2fd = PanelWidget(
        widget_id="06edd2fd-0982-4001-bebc-f0996a961001",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    root.add_child(w_06edd2fd)
    # Children of w_06edd2fd
    # label: Untitled
    w_945e0682 = LabelWidget(
        widget_id="945e0682-c206-4be2-9fe0-01c0e84edd83",
        label="Untitled",
        visible=True,
        enabled=True,
    )
    w_06edd2fd.add_child(w_945e0682)
    # panel: 9a8e5aa3
    w_9a8e5aa3 = PanelWidget(
        widget_id="9a8e5aa3-aa7b-4a3c-ab53-67d6788c0d72",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_06edd2fd.add_child(w_9a8e5aa3)
    # Children of w_9a8e5aa3
    # button: New Task
    w_0708ad47 = ButtonWidget(
        widget_id="0708ad47-5112-4f4f-9061-9f0e11a1f92d",
        label="New Task",
        visible=True,
        enabled=True,
        metadata={"variant": "primary"},
    )
    w_9a8e5aa3.add_child(w_0708ad47)
    # Event handlers for w_0708ad47
    w_0708ad47.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))
    # button: Settings
    w_d99e9fde = ButtonWidget(
        widget_id="d99e9fde-9300-43f1-941d-fd6cebf06f05",
        label="Settings",
        visible=True,
        enabled=True,
        metadata={"variant": "secondary"},
    )
    w_9a8e5aa3.add_child(w_d99e9fde)
    # Event handlers for w_d99e9fde
    w_d99e9fde.on("click", lambda d, a="jaya:open_dialog", p={}: jaya_dispatch(a, p))
    # panel: 094e9e24
    w_094e9e24 = PanelWidget(
        widget_id="094e9e24-9e67-4e65-bb6a-bf51edd1f7fd",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_094e9e24)
    # Children of w_094e9e24
    # panel: dabbc93b
    w_dabbc93b = PanelWidget(
        widget_id="dabbc93b-53ed-4105-84db-d119b93a1059",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_094e9e24.add_child(w_dabbc93b)
    # Children of w_dabbc93b
    # panel: f6cd9187
    w_f6cd9187 = PanelWidget(
        widget_id="f6cd9187-ed01-4c1a-b14c-0f126bc256a5",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_dabbc93b.add_child(w_f6cd9187)
    # Children of w_f6cd9187
    # label: Total Tasks
    w_552154d6 = LabelWidget(
        widget_id="552154d6-e45d-4c4d-815e-3f4786db16bd",
        label="Total Tasks",
        visible=True,
        enabled=True,
    )
    w_f6cd9187.add_child(w_552154d6)
    # label: 1,234
    w_b78c23e8 = LabelWidget(
        widget_id="b78c23e8-d965-4f48-b511-7b6ffba04156",
        label="1,234",
        visible=True,
        enabled=True,
    )
    w_f6cd9187.add_child(w_b78c23e8)
    # label: +12%
    w_1be6dcad = LabelWidget(
        widget_id="1be6dcad-7a7f-4af1-baa2-f1258c327f9b",
        label="+12%",
        visible=True,
        enabled=True,
    )
    w_f6cd9187.add_child(w_1be6dcad)
    # panel: 36b5acf3
    w_36b5acf3 = PanelWidget(
        widget_id="36b5acf3-2036-4fe3-b2d0-d5ae57a3f7ff",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_dabbc93b.add_child(w_36b5acf3)
    # Children of w_36b5acf3
    # label: Completed
    w_7c123983 = LabelWidget(
        widget_id="7c123983-ea39-4d36-9fd6-57ef0b0e2618",
        label="Completed",
        visible=True,
        enabled=True,
    )
    w_36b5acf3.add_child(w_7c123983)
    # label: 987
    w_d1d3987d = LabelWidget(
        widget_id="d1d3987d-c771-41e6-84db-9a6c2b2820db",
        label="987",
        visible=True,
        enabled=True,
    )
    w_36b5acf3.add_child(w_d1d3987d)
    # label: +8%
    w_4b01305b = LabelWidget(
        widget_id="4b01305b-626e-4b35-b844-347cab90caa0",
        label="+8%",
        visible=True,
        enabled=True,
    )
    w_36b5acf3.add_child(w_4b01305b)
    # panel: bb55f719
    w_bb55f719 = PanelWidget(
        widget_id="bb55f719-6119-4be6-9a1b-d597f96e1552",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_dabbc93b.add_child(w_bb55f719)
    # Children of w_bb55f719
    # label: In Progress
    w_b92eb111 = LabelWidget(
        widget_id="b92eb111-ac5f-4815-ad30-398bfbe7cf4b",
        label="In Progress",
        visible=True,
        enabled=True,
    )
    w_bb55f719.add_child(w_b92eb111)
    # label: 156
    w_34e2455e = LabelWidget(
        widget_id="34e2455e-cc44-4645-8060-0a336197bfeb",
        label="156",
        visible=True,
        enabled=True,
    )
    w_bb55f719.add_child(w_34e2455e)
    # label: -3%
    w_478ff298 = LabelWidget(
        widget_id="478ff298-aafa-4c0a-a156-560490d0a24a",
        label="-3%",
        visible=True,
        enabled=True,
    )
    w_bb55f719.add_child(w_478ff298)
    # panel: 54883d17
    w_54883d17 = PanelWidget(
        widget_id="54883d17-c7d6-49df-8824-1938d0f256ce",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_dabbc93b.add_child(w_54883d17)
    # Children of w_54883d17
    # label: Overdue
    w_8d881041 = LabelWidget(
        widget_id="8d881041-c6ce-482d-a5bb-5e22bc8332a9",
        label="Overdue",
        visible=True,
        enabled=True,
    )
    w_54883d17.add_child(w_8d881041)
    # label: 12
    w_86bfa4ce = LabelWidget(
        widget_id="86bfa4ce-331f-4b36-85f9-5b7cf4f803ca",
        label="12",
        visible=True,
        enabled=True,
    )
    w_54883d17.add_child(w_86bfa4ce)
    # label: +2%
    w_56d9f5ac = LabelWidget(
        widget_id="56d9f5ac-1381-464e-b23e-e74e85482574",
        label="+2%",
        visible=True,
        enabled=True,
    )
    w_54883d17.add_child(w_56d9f5ac)

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.
    
    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict
        
    Returns:
        Result dict with status and any output data
    """
    config = config or {}
    
    # Build scene
    root = build_scene_99fbade1()
    
    # Initialize runtime
    from jaya_core.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="99fbade1",
        feature_name="dashboard",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )
    
    # Set global runtime reference for dispatch
    set_runtime(runtime)
    
    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))
    
    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "dashboard"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

def feature_manifest() -> Dict[str, Any]:
    """Return the generated feature's registration contract."""
    return {
        "name": FEATURE_NAME,
        "id": FEATURE_ID,
        "version": FEATURE_VERSION,
        "description": FEATURE_DESCRIPTION,
        "protocol_version": FEATURE_PROTOCOL_VERSION,
        "entry_point": "run_feature",
        "capabilities": ["ui", "events", "state", "jaya_actions"],
        "permissions": ["ui_mount", "state_read", "state_write", "api_call"],
    }

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.
    
    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action
        
    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}
    
    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        print(f"Warning: No JAYA bridge set, action {action} dropped")
        return None
    
    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as e:
        print(f"JAYA dispatch error: {e}")
        return None

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
