"""
Test Dialog - JAYA Dynamic Feature
Auto-generated by FeatureCompiler v0.1
"""
from .test_dialog import run_feature, feature_manifest, set_jaya_bridge, jaya_dispatch

__all__ = ["run_feature", "feature_manifest", "set_jaya_bridge", "jaya_dispatch"]
