"""
JAYA Dynamic Feature: Settings
Generated by FeatureCompiler v0.1
Feature ID: 6d48ac4d
Description: Application settings and preferences

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "settings_dialog"
FEATURE_ID = "6d48ac4d"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Application settings and preferences"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from src.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from src.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class TextInputWidget(WidgetBase):
    """Text Input widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="text_input", **kwargs)
        self._value = kwargs.get('value', '')
        self.placeholder = kwargs.get('placeholder', '')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_value":
            self._value = payload.get("value", "")
            self.emit("change", {"value": self._value})
            return {"value": self._value}
        elif action == "get_value":
            return {"value": self._value}
        elif action == "focus":
            self.emit("focus", {})
            return {"focused": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_6d48ac4d() -> WidgetBase:
    """Build the "Settings" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="edb4d085-9aac-4653-9be3-0537ae1cbdf9",
        label="Untitled",
        layout="flex_col",
        rect={"x": {"value": 0, "unit": "px"}, "y": {"value": 0, "unit": "px"}, "width": {"value": 600.0, "unit": "px"}, "height": {"value": 700.0, "unit": "px"}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: 2b136fbf
    w_2b136fbf = PanelWidget(
        widget_id="2b136fbf-400d-401b-aa8c-3b0236d79bb6",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_2b136fbf)
    # Children of w_2b136fbf
    # label: Untitled
    w_006c06c6 = LabelWidget(
        widget_id="006c06c6-2053-426b-97f3-af4ccea82309",
        label="Untitled",
        visible=True,
        enabled=True,
    )
    w_2b136fbf.add_child(w_006c06c6)
    # panel: 454a816f
    w_454a816f = PanelWidget(
        widget_id="454a816f-e834-4448-9fc3-2614b5c75906",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_2b136fbf.add_child(w_454a816f)
    # Children of w_454a816f
    # label: General
    w_160d8694 = LabelWidget(
        widget_id="160d8694-8208-4896-9589-f6b632015e7f",
        label="General",
        visible=True,
        enabled=True,
    )
    w_454a816f.add_child(w_160d8694)
    # text_input: c072c999
    w_c072c999 = TextInputWidget(
        widget_id="c072c999-a1ca-404c-a33c-d8cb32ff6d56",
        label="",
        visible=True,
        enabled=True,
        value="",
        placeholder="Your name",
    )
    w_454a816f.add_child(w_c072c999)
    # label: Select: Language
    w_dda53991 = LabelWidget(
        widget_id="dda53991-6e6d-4182-8602-e870914eba9f",
        label="Select: Language",
        visible=True,
        enabled=True,
    )
    w_454a816f.add_child(w_dda53991)
    # label: Select: Theme
    w_0e7eca64 = LabelWidget(
        widget_id="0e7eca64-4af9-404a-bfb9-c6fedc7753dc",
        label="Select: Theme",
        visible=True,
        enabled=True,
    )
    w_454a816f.add_child(w_0e7eca64)
    # panel: f8fcdde3
    w_f8fcdde3 = PanelWidget(
        widget_id="f8fcdde3-1e74-4aec-b1f9-4d5947e5ed57",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_2b136fbf.add_child(w_f8fcdde3)
    # Children of w_f8fcdde3
    # label: Privacy & Security
    w_11682a36 = LabelWidget(
        widget_id="11682a36-ce81-4e34-b1cb-f8ef6104bb45",
        label="Privacy & Security",
        visible=True,
        enabled=True,
    )
    w_f8fcdde3.add_child(w_11682a36)
    # label: Checkbox: Allow anonymous usage analytics
    w_7733a20b = LabelWidget(
        widget_id="7733a20b-15c6-4da7-864e-56ff062f3bd0",
        label="Checkbox: Allow anonymous usage analytics",
        visible=True,
        enabled=True,
    )
    w_f8fcdde3.add_child(w_7733a20b)
    # label: Checkbox: Crash reporting
    w_55e72b65 = LabelWidget(
        widget_id="55e72b65-d0bc-4449-a194-0f16bbf8d7b2",
        label="Checkbox: Crash reporting",
        visible=True,
        enabled=True,
    )
    w_f8fcdde3.add_child(w_55e72b65)
    # label: Checkbox: Auto-update
    w_4635e3c0 = LabelWidget(
        widget_id="4635e3c0-97b7-471c-87bc-a035f067dfc5",
        label="Checkbox: Auto-update",
        visible=True,
        enabled=True,
    )
    w_f8fcdde3.add_child(w_4635e3c0)
    # panel: 94a332a6
    w_94a332a6 = PanelWidget(
        widget_id="94a332a6-dedf-44ce-b9be-6a16fc5a635c",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_2b136fbf.add_child(w_94a332a6)
    # Children of w_94a332a6
    # label: Notifications
    w_892dbd72 = LabelWidget(
        widget_id="892dbd72-b3fb-48ef-957d-08bd704d7cc6",
        label="Notifications",
        visible=True,
        enabled=True,
    )
    w_94a332a6.add_child(w_892dbd72)
    # label: Checkbox: Email notifications
    w_ae268478 = LabelWidget(
        widget_id="ae268478-8253-45cd-8700-521b38020d9f",
        label="Checkbox: Email notifications",
        visible=True,
        enabled=True,
    )
    w_94a332a6.add_child(w_ae268478)
    # label: Checkbox: Push notifications
    w_fe63dd1d = LabelWidget(
        widget_id="fe63dd1d-8adf-4eb2-8af9-fb3d1f147f8c",
        label="Checkbox: Push notifications",
        visible=True,
        enabled=True,
    )
    w_94a332a6.add_child(w_fe63dd1d)
    # label: Select: Frequency
    w_2d8cc51c = LabelWidget(
        widget_id="2d8cc51c-e8f9-4656-ae6a-d00798d09363",
        label="Select: Frequency",
        visible=True,
        enabled=True,
    )
    w_94a332a6.add_child(w_2d8cc51c)
    # panel: 0403f293
    w_0403f293 = PanelWidget(
        widget_id="0403f293-f48d-410d-b8a0-bd610f45c945",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_2b136fbf.add_child(w_0403f293)
    # Children of w_0403f293
    # button: Cancel
    w_e7b13a45 = ButtonWidget(
        widget_id="e7b13a45-df3b-48ca-a09f-a1436ec01acd",
        label="Cancel",
        visible=True,
        enabled=True,
        metadata={"variant": "secondary"},
    )
    w_0403f293.add_child(w_e7b13a45)
    # Event handlers for w_e7b13a45
    w_e7b13a45.on("click", lambda d, a="jaya:close_dialog", p={}: jaya_dispatch(a, p))
    # button: Save Changes
    w_63d72318 = ButtonWidget(
        widget_id="63d72318-b0da-4697-aa63-4947ceba17c3",
        label="Save Changes",
        visible=True,
        enabled=True,
        metadata={"variant": "primary"},
    )
    w_0403f293.add_child(w_63d72318)
    # Event handlers for w_63d72318
    w_63d72318.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.

    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict

    Returns:
        Result dict with status and any output data
    """
    config = config or {}

    # Build scene
    root = build_scene_6d48ac4d()

    # Initialize runtime
    from src.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="6d48ac4d",
        feature_name="settings_dialog",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )

    # Set global runtime reference for dispatch
    set_runtime(runtime)

    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))

    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "settings_dialog"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.

    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action

    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}

    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        print(f"Warning: No JAYA bridge set, action {action} dropped")
        return None

    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as e:
        print(f"JAYA dispatch error: {e}")
        return None

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
