import os
import sys
import requests
import json
from pathlib import Path
from dotenv import load_dotenv

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.append(str(PROJECT_ROOT))
load_dotenv(PROJECT_ROOT / ".env")

from src.research.video_processor import VideoProcessor

def generate_knowledge_synthesis(all_reports_content):
    """
    Synthesize multiple video reports into a single Knowledge Artifact using Llama 3.1 Nemotron.
    """
    print("\n[SYNTHESIS] Generating Consolidated Knowledge Artifact...")
    
    api_key = os.getenv("NVIDIA_API_KEY")
    if not api_key:
        print("❌ Error: NVIDIA_API_KEY not found in .env")
        return "Knowledge Synthesis Skipped (No API Key)"
        
    model = os.getenv("NVIDIA_LLAMA3.1_MODEL")
    base_url = os.getenv("NVIDIA_LLAMA3.1_BASE_URL")
    
    if not model or not base_url:
         print("❌ Error: Llama 3.1 Model/URL not configured!")
         return "Knowledge Synthesis Skipped (Config Missing)"
         
    invoke_url = f"{base_url}/chat/completions"
    
    prompt = f"""
    You are JAYA_RESEARCH, an advanced AI Researcher.
    
    TASK:
    Analyze the following raw observational reports from a long video analysis session. 
    Synthesize them into a single structured "KNOWLEDGE ARTIFACT" (Markdown).
    
    The raw reports are generated by a "Smart Sensing" system (Silence-Aware Audio + Scene-Aware Visuals).
    
    YOUR GOAL:
    Extract *High-Fidelity Knowledge* from these observations.
    
    OUTPUT FORMAT:
    # Title
    ## 1. Executive Summary
    ## 2. Key Technical Concepts (Definitions & Relationships)
    ## 3. Detected Processes / Workflows (Step-by-Step)
    ## 4. Q&A Extraction (What questions were asked and answered?)
    ## 5. Visual Evidence (What specific diagrams/slides were shown?)
    
    RAW REPORTS:
    {all_reports_content}
    """
    
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 4096,
        "temperature": 0.3, # Lower temperature for factual accuracy
        "top_p": 0.95
    }
    
    try:
        response = requests.post(invoke_url, headers=headers, json=payload)
        response.raise_for_status()
        content = response.json()['choices'][0]['message']['content']
        return content
    except Exception as e:
        error_details = str(e)
        if 'response' in locals():
            error_details += f"\nResponse Body: {response.text}"
        print(f"[SYNTHESIS FAILED] {error_details}")
        return f"Failed to synthesize knowledge. Error: {error_details}"

def test_batch_process():
    input_dir_env = os.getenv("VIDEO_INPUT_DIR")
    if not input_dir_env:
        # Fallback to relative path if not set, or error
        input_dir = PROJECT_ROOT / "file-uji-coba"
    else:
        input_dir = Path(input_dir_env)
        
    if not input_dir.exists():
        print(f"Error: Directory {input_dir} not found.")
        return

    processor = VideoProcessor()
    
    # List ALL video files but filter for the long one for testing
    all_videos = list(input_dir.glob("*.mp4"))
    video_files = [v for v in all_videos if "10-23-26" in v.name]
    
    if not video_files:
        print("Target video not found, reverting to all videos.")
        video_files = all_videos

    print(f"Found {len(video_files)} videos to process (Targeting 10-23-26)")

    results_dir = PROJECT_ROOT / "reports" / "video_analysis"
    results_dir.mkdir(parents=True, exist_ok=True)
    
    aggregated_content = ""

    for i, video_file in enumerate(video_files):
        print(f"\n[{i+1}/{len(video_files)}] Processing: {video_file.name}...")
        try:
            # Process video (Chunked Strategy)
            result = processor.process_video_chunked(str(video_file))
            
            # Save individual report
            report_path = results_dir / f"{video_file.stem}_report.md"
            with open(report_path, "w", encoding="utf-8") as f:
                f.write(result['report'])
            
            print(f"✅ Report saved: {report_path.name}")
            
            # Add to aggregation
            aggregated_content += f"\n\n=== SOURCE VIDEO: {video_file.name} ===\n"
            aggregated_content += result['report']
            
        except Exception as e:
            print(f"❌ Failed to process {video_file.name}: {e}")
            import traceback
            traceback.print_exc()

    # Generate Final Consolidated Knowledge
    if aggregated_content:
        knowledge = generate_knowledge_synthesis(aggregated_content)
        
        knowledge_path = results_dir / "CONSOLIDATED_KNOWLEDGE.md"
        with open(knowledge_path, "w", encoding="utf-8") as f:
            f.write(knowledge)
            
        print(f"\n✅✅ KNOWLEDGE SYNTHESIS COMPLETE!")
        print(f"File: {knowledge_path}")

if __name__ == "__main__":
    test_batch_process()
