import json
import os
import time
import uuid
from typing import Dict, Any, List

class ExperimentTracker:
    """
    Tracks research experiments for reproducible science.
    Saves logs to data/experiments/
    """
    def __init__(self, base_dir="data/experiments"):
        self.base_dir = base_dir
        os.makedirs(self.base_dir, exist_ok=True)
        self.current_experiment_id = None

    def start_experiment(self, name: str, config: Dict[str, Any] = None) -> str:
        """
        Starts a new experiment session.
        """
        self.current_experiment_id = f"{int(time.time())}_{uuid.uuid4().hex[:6]}"
        exp_data = {
            "id": self.current_experiment_id,
            "name": name,
            "timestamp": time.time(),
            "status": "RUNNING",
            "config": config or {},
            "metrics": {},
            "logs": []
        }
        self._save(exp_data)
        print(f"[Tracker] Started Experiment: {name} ({self.current_experiment_id})")
        return self.current_experiment_id

    def log_metric(self, key: str, value: Any, step: int = None):
        """
        Logs a quantitative metric (e.g., accuracy, speed, memory).
        """
        if not self.current_experiment_id:
            print("[Tracker] Warning: No active experiment to log metric.")
            return

        exp_data = self._load(self.current_experiment_id)
        if key not in exp_data["metrics"]:
            exp_data["metrics"][key] = []
        
        entry = {"value": value, "time": time.time()}
        if step is not None:
            entry["step"] = step
            
        exp_data["metrics"][key].append(entry)
        self._save(exp_data)

    def log_artifact(self, filename: str, content: str):
        """
        Saves a file generated by the experiment.
        """
        if not self.current_experiment_id:
            return
            
        exp_dir = os.path.join(self.base_dir, self.current_experiment_id)
        os.makedirs(exp_dir, exist_ok=True)
        
        with open(os.path.join(exp_dir, filename), "w", encoding="utf-8") as f:
            f.write(content)

    def end_experiment(self, status: str = "COMPLETED", result_summary: str = ""):
        """
        Finalizes the experiment.
        """
        if not self.current_experiment_id:
            return

        exp_data = self._load(self.current_experiment_id)
        exp_data["status"] = status
        exp_data["end_time"] = time.time()
        exp_data["summary"] = result_summary
        self._save(exp_data)
        print(f"[Tracker] Experiment Ended: {status}")
        self.current_experiment_id = None

    def _save(self, data: Dict):
        path = os.path.join(self.base_dir, f"{data['id']}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)

    def _load(self, exp_id: str) -> Dict:
        path = os.path.join(self.base_dir, f"{exp_id}.json")
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        return {}

    def generate_chart(self, exp_id: str, metric_key: str):
        """
        Generates a PNG chart for a specific metric in an experiment.
        """
        try:
            import matplotlib.pyplot as plt
            import matplotlib
            matplotlib.use('Agg') # Non-interactive backend
            
            data = self._load(exp_id)
            if not data or metric_key not in data.get("metrics", {}):
                return None
                
            entries = data["metrics"][metric_key]
            values = [e["value"] for e in entries]
            steps = [e.get("step", i) for i, e in enumerate(entries)]
            
            plt.figure(figsize=(10, 6))
            plt.plot(steps, values, marker='o', linestyle='-')
            plt.title(f"Experiment {exp_id}: {metric_key}")
            plt.xlabel("Step")
            plt.ylabel(metric_key)
            plt.grid(True)
            
            # Save chart
            exp_dir = os.path.join(self.base_dir, exp_id)
            os.makedirs(exp_dir, exist_ok=True)
            chart_path = os.path.join(exp_dir, f"{metric_key}.png")
            plt.savefig(chart_path)
            plt.close()
            
            return chart_path
        except ImportError:
            print("[Tracker] Matplotlib not installed. Skipping chart generation.")
            return None

if __name__ == "__main__":
    # Test
    tracker = ExperimentTracker()
    eid = tracker.start_experiment("Optimization Test", config={"learning_rate": 0.01})
    tracker.log_metric("accuracy", 0.1, step=1)
    tracker.log_metric("accuracy", 0.4, step=2)
    tracker.log_metric("accuracy", 0.8, step=3)
    tracker.log_metric("accuracy", 0.95, step=4)
    tracker.end_experiment("SUCCESS", "Achieved 95% accuracy")
    
    print(f"Chart generated: {tracker.generate_chart(eid, 'accuracy')}")
