"""
JAYA Dynamic Feature: Dashboard
Generated by FeatureCompiler v0.1
Feature ID: 9c2ce822-f56c-40a7-94ef-446a977258c0
Description: Main dashboard with metrics and quick actions

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "dashboard"
FEATURE_ID = "9c2ce822-f56c-40a7-94ef-446a977258c0"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Main dashboard with metrics and quick actions"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from src.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from src.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_9c2ce822() -> WidgetBase:
    """Build the "Dashboard" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="ac4211a0-327e-4bd8-ba1c-d61591ba5e01",
        label="Untitled",
        layout="flex_col",
        rect={"x": {"value": 0, "unit": "px"}, "y": {"value": 0, "unit": "px"}, "width": {"value": 1200.0, "unit": "px"}, "height": {"value": 800.0, "unit": "px"}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: 7ae09a82
    w_7ae09a82 = PanelWidget(
        widget_id="7ae09a82-2fec-4105-b516-115ffc654661",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    root.add_child(w_7ae09a82)
    # Children of w_7ae09a82
    # label: Untitled
    w_0abd0c6e = LabelWidget(
        widget_id="0abd0c6e-0b39-48cd-94d6-de020c768c0c",
        label="Untitled",
        visible=True,
        enabled=True,
    )
    w_7ae09a82.add_child(w_0abd0c6e)
    # panel: aa36cd32
    w_aa36cd32 = PanelWidget(
        widget_id="aa36cd32-be64-4cae-94b0-cf9a0d1ae8fb",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_7ae09a82.add_child(w_aa36cd32)
    # Children of w_aa36cd32
    # button: New Task
    w_bbcda980 = ButtonWidget(
        widget_id="bbcda980-0998-46c5-9a45-e4253135e8f3",
        label="New Task",
        visible=True,
        enabled=True,
        metadata={"variant": "primary"},
    )
    w_aa36cd32.add_child(w_bbcda980)
    # Event handlers for w_bbcda980
    w_bbcda980.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))
    # button: Settings
    w_170cd7c0 = ButtonWidget(
        widget_id="170cd7c0-31d7-4f4c-a50d-b079717a1dcd",
        label="Settings",
        visible=True,
        enabled=True,
        metadata={"variant": "secondary"},
    )
    w_aa36cd32.add_child(w_170cd7c0)
    # Event handlers for w_170cd7c0
    w_170cd7c0.on("click", lambda d, a="jaya:open_dialog", p={}: jaya_dispatch(a, p))
    # panel: 26bc4e2d
    w_26bc4e2d = PanelWidget(
        widget_id="26bc4e2d-6368-449b-aeea-4dce91bbe7cd",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_26bc4e2d)
    # Children of w_26bc4e2d
    # panel: d3578635
    w_d3578635 = PanelWidget(
        widget_id="d3578635-9a96-406b-b324-98f9e527ba79",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_26bc4e2d.add_child(w_d3578635)
    # Children of w_d3578635
    # panel: d744de89
    w_d744de89 = PanelWidget(
        widget_id="d744de89-7f81-4d35-a545-d2f1b4eda0e9",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_d3578635.add_child(w_d744de89)
    # Children of w_d744de89
    # label: Total Tasks
    w_7e433244 = LabelWidget(
        widget_id="7e433244-3f0a-4452-b9f0-838945620c8a",
        label="Total Tasks",
        visible=True,
        enabled=True,
    )
    w_d744de89.add_child(w_7e433244)
    # label: 1,234
    w_c4edfc37 = LabelWidget(
        widget_id="c4edfc37-9d58-41be-8d66-b018a4ce1daa",
        label="1,234",
        visible=True,
        enabled=True,
    )
    w_d744de89.add_child(w_c4edfc37)
    # label: +12%
    w_3fad29c4 = LabelWidget(
        widget_id="3fad29c4-e0b3-4db5-b996-e4109b1e3a61",
        label="+12%",
        visible=True,
        enabled=True,
    )
    w_d744de89.add_child(w_3fad29c4)
    # panel: 69f864a0
    w_69f864a0 = PanelWidget(
        widget_id="69f864a0-0f06-4fb0-a08d-767c14394674",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_d3578635.add_child(w_69f864a0)
    # Children of w_69f864a0
    # label: Completed
    w_a94d57b1 = LabelWidget(
        widget_id="a94d57b1-fd56-4eb5-91ad-694199c59a9b",
        label="Completed",
        visible=True,
        enabled=True,
    )
    w_69f864a0.add_child(w_a94d57b1)
    # label: 987
    w_996bf08b = LabelWidget(
        widget_id="996bf08b-c33b-4e8e-afb2-87755f17da84",
        label="987",
        visible=True,
        enabled=True,
    )
    w_69f864a0.add_child(w_996bf08b)
    # label: +8%
    w_07869394 = LabelWidget(
        widget_id="07869394-7b84-45b2-b98f-ed1440ce73be",
        label="+8%",
        visible=True,
        enabled=True,
    )
    w_69f864a0.add_child(w_07869394)
    # panel: b8f5a4ea
    w_b8f5a4ea = PanelWidget(
        widget_id="b8f5a4ea-9840-481f-83ec-11c9a8b4b02a",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_d3578635.add_child(w_b8f5a4ea)
    # Children of w_b8f5a4ea
    # label: In Progress
    w_b96b2693 = LabelWidget(
        widget_id="b96b2693-16ad-46c2-8eed-da959e748c88",
        label="In Progress",
        visible=True,
        enabled=True,
    )
    w_b8f5a4ea.add_child(w_b96b2693)
    # label: 156
    w_fee719dd = LabelWidget(
        widget_id="fee719dd-50d9-405e-ab98-25cff2090aff",
        label="156",
        visible=True,
        enabled=True,
    )
    w_b8f5a4ea.add_child(w_fee719dd)
    # label: -3%
    w_73359c7d = LabelWidget(
        widget_id="73359c7d-616a-4431-8444-40845f544f71",
        label="-3%",
        visible=True,
        enabled=True,
    )
    w_b8f5a4ea.add_child(w_73359c7d)
    # panel: aac1081c
    w_aac1081c = PanelWidget(
        widget_id="aac1081c-e225-4555-aecb-969251b75041",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_d3578635.add_child(w_aac1081c)
    # Children of w_aac1081c
    # label: Overdue
    w_53633787 = LabelWidget(
        widget_id="53633787-23d1-435b-9c6d-fa13107c70eb",
        label="Overdue",
        visible=True,
        enabled=True,
    )
    w_aac1081c.add_child(w_53633787)
    # label: 12
    w_151434a3 = LabelWidget(
        widget_id="151434a3-ee7e-4831-a148-2cadd12ee446",
        label="12",
        visible=True,
        enabled=True,
    )
    w_aac1081c.add_child(w_151434a3)
    # label: +2%
    w_eab1111b = LabelWidget(
        widget_id="eab1111b-42d6-4454-ba13-9f5fbe9df1d6",
        label="+2%",
        visible=True,
        enabled=True,
    )
    w_aac1081c.add_child(w_eab1111b)

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.

    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict

    Returns:
        Result dict with status and any output data
    """
    config = config or {}

    # Build scene
    root = build_scene_9c2ce822()

    # Initialize runtime
    from src.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="9c2ce822-f56c-40a7-94ef-446a977258c0",
        feature_name="dashboard",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )

    # Set global runtime reference for dispatch
    set_runtime(runtime)

    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))

    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "dashboard"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

def feature_manifest() -> Dict[str, Any]:
    """Return the generated feature's registration contract."""
    return {
        "name": FEATURE_NAME,
        "id": FEATURE_ID,
        "version": FEATURE_VERSION,
        "description": FEATURE_DESCRIPTION,
        "protocol_version": FEATURE_PROTOCOL_VERSION,
        "entry_point": "run_feature",
        "capabilities": ["ui", "events", "state", "jaya_actions"],
        "permissions": ["ui_mount", "state_read", "state_write", "api_call"],
    }

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.

    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action

    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}

    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        print(f"Warning: No JAYA bridge set, action {action} dropped")
        return None

    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as e:
        print(f"JAYA dispatch error: {e}")
        return None

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
