"""
JAYA Dynamic Feature: Settings
Generated by FeatureCompiler v0.1
Feature ID: ba80db10-cdf1-4b23-90ee-69c13a508b59
Description: Application settings and preferences

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "settings_dialog"
FEATURE_ID = "ba80db10-cdf1-4b23-90ee-69c13a508b59"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Application settings and preferences"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from src.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from src.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class TextInputWidget(WidgetBase):
    """Text Input widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="text_input", **kwargs)
        self._value = kwargs.get('value', '')
        self.placeholder = kwargs.get('placeholder', '')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_value":
            self._value = payload.get("value", "")
            self.emit("change", {"value": self._value})
            return {"value": self._value}
        elif action == "get_value":
            return {"value": self._value}
        elif action == "focus":
            self.emit("focus", {})
            return {"focused": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_ba80db10() -> WidgetBase:
    """Build the "Settings" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="28afd3d9-448f-42f2-a39d-5beff45fb8fb",
        label="Untitled",
        layout="flex_col",
        rect={'x': {'value': 0, 'unit': 'px'}, 'y': {'value': 0, 'unit': 'px'}, 'width': {'value': 600.0, 'unit': 'px'}, 'height': {'value': 700.0, 'unit': 'px'}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: 24279b82
    w_24279b82 = PanelWidget(
        widget_id="24279b82-063e-4e88-bbde-313f68c5cbac",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_24279b82)
    # Children of w_24279b82
    # label: Untitled
    w_17863488 = LabelWidget(
        widget_id="17863488-98a3-43be-a397-6f3b05a01492",
        label="Untitled",
        visible=True,
        enabled=True,
    )
    w_24279b82.add_child(w_17863488)
    # panel: 2bfe8e8f
    w_2bfe8e8f = PanelWidget(
        widget_id="2bfe8e8f-a7c7-445b-ad41-de94eec57457",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_24279b82.add_child(w_2bfe8e8f)
    # Children of w_2bfe8e8f
    # label: General
    w_3d9242aa = LabelWidget(
        widget_id="3d9242aa-7c7d-405f-9d47-750780fac170",
        label="General",
        visible=True,
        enabled=True,
    )
    w_2bfe8e8f.add_child(w_3d9242aa)
    # text_input: 90228113
    w_90228113 = TextInputWidget(
        widget_id="90228113-4378-437c-ad82-4492918e661d",
        label="",
        visible=True,
        enabled=True,
        value='',
        placeholder="Your name",
    )
    w_2bfe8e8f.add_child(w_90228113)
    # label: Select: Language
    w_46058e18 = LabelWidget(
        widget_id="46058e18-8701-4490-bf1d-166c8368af0f",
        label="Select: Language",
        visible=True,
        enabled=True,
    )
    w_2bfe8e8f.add_child(w_46058e18)
    # label: Select: Theme
    w_fcf849fe = LabelWidget(
        widget_id="fcf849fe-0e43-4624-a7b4-60b4ab00f108",
        label="Select: Theme",
        visible=True,
        enabled=True,
    )
    w_2bfe8e8f.add_child(w_fcf849fe)
    # panel: b495096a
    w_b495096a = PanelWidget(
        widget_id="b495096a-a98f-4ff5-9ffc-4e7ac3d15672",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_24279b82.add_child(w_b495096a)
    # Children of w_b495096a
    # label: Privacy & Security
    w_46e08230 = LabelWidget(
        widget_id="46e08230-2f2f-4594-8486-5d4953ed152e",
        label="Privacy & Security",
        visible=True,
        enabled=True,
    )
    w_b495096a.add_child(w_46e08230)
    # label: Checkbox: Allow anonymous usage analytics
    w_7b4551f3 = LabelWidget(
        widget_id="7b4551f3-8dd8-488d-8360-50fc9c0789ef",
        label="Checkbox: Allow anonymous usage analytics",
        visible=True,
        enabled=True,
    )
    w_b495096a.add_child(w_7b4551f3)
    # label: Checkbox: Crash reporting
    w_9374b6fc = LabelWidget(
        widget_id="9374b6fc-00bb-480a-8003-6cd2547224e9",
        label="Checkbox: Crash reporting",
        visible=True,
        enabled=True,
    )
    w_b495096a.add_child(w_9374b6fc)
    # label: Checkbox: Auto-update
    w_8e8f684b = LabelWidget(
        widget_id="8e8f684b-8d95-41ec-aa60-875b728758c2",
        label="Checkbox: Auto-update",
        visible=True,
        enabled=True,
    )
    w_b495096a.add_child(w_8e8f684b)
    # panel: 1bd6bd62
    w_1bd6bd62 = PanelWidget(
        widget_id="1bd6bd62-5a65-4a2a-a048-a2d1919b208e",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_24279b82.add_child(w_1bd6bd62)
    # Children of w_1bd6bd62
    # label: Notifications
    w_478cdfc4 = LabelWidget(
        widget_id="478cdfc4-e9f2-4238-a0e2-9e7538cd1ddb",
        label="Notifications",
        visible=True,
        enabled=True,
    )
    w_1bd6bd62.add_child(w_478cdfc4)
    # label: Checkbox: Email notifications
    w_751ac04b = LabelWidget(
        widget_id="751ac04b-e030-4170-93ba-0f778c87a800",
        label="Checkbox: Email notifications",
        visible=True,
        enabled=True,
    )
    w_1bd6bd62.add_child(w_751ac04b)
    # label: Checkbox: Push notifications
    w_3a9a8b43 = LabelWidget(
        widget_id="3a9a8b43-96ac-4b0b-ba70-830783875e53",
        label="Checkbox: Push notifications",
        visible=True,
        enabled=True,
    )
    w_1bd6bd62.add_child(w_3a9a8b43)
    # label: Select: Frequency
    w_981cbd14 = LabelWidget(
        widget_id="981cbd14-0fbf-4541-bb9b-068ec22dd22f",
        label="Select: Frequency",
        visible=True,
        enabled=True,
    )
    w_1bd6bd62.add_child(w_981cbd14)
    # panel: da8fbbca
    w_da8fbbca = PanelWidget(
        widget_id="da8fbbca-399e-4f8a-b7ae-354197f5405a",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_24279b82.add_child(w_da8fbbca)
    # Children of w_da8fbbca
    # button: Cancel
    w_fd5bc8ed = ButtonWidget(
        widget_id="fd5bc8ed-2681-4af1-8087-26000e002aed",
        label="Cancel",
        visible=True,
        enabled=True,
        metadata={'variant': 'secondary'},
    )
    w_da8fbbca.add_child(w_fd5bc8ed)
    # Event handlers for w_fd5bc8ed
    w_fd5bc8ed.on("click", lambda d, a="jaya:close_dialog", p={}: jaya_dispatch(a, p))
    # button: Save Changes
    w_e764f2de = ButtonWidget(
        widget_id="e764f2de-f37e-4328-92f7-e3504e152869",
        label="Save Changes",
        visible=True,
        enabled=True,
        metadata={'variant': 'primary'},
    )
    w_da8fbbca.add_child(w_e764f2de)
    # Event handlers for w_e764f2de
    w_e764f2de.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.

    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict

    Returns:
        Result dict with status and any output data
    """
    config = config or {}

    # Build scene
    root = build_scene_ba80db10()

    # Initialize runtime
    from src.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="ba80db10-cdf1-4b23-90ee-69c13a508b59",
        feature_name="settings_dialog",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )

    # Set global runtime reference for dispatch
    set_runtime(runtime)

    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))

    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "settings_dialog"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

def feature_manifest() -> Dict[str, Any]:
    """Return the generated feature's registration contract."""
    return {
        "name": FEATURE_NAME,
        "id": FEATURE_ID,
        "version": FEATURE_VERSION,
        "description": FEATURE_DESCRIPTION,
        "protocol_version": FEATURE_PROTOCOL_VERSION,
        "entry_point": "run_feature",
        "capabilities": ["ui", "events", "state", "jaya_actions"],
        "permissions": ["ui_mount", "state_read", "state_write", "api_call"],
    }

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.

    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action

    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}

    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        return {
            "success": False,
            "error_code": "BRIDGE_UNAVAILABLE",
            "action": action,
        }

    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as exc:
        return {
            "success": False,
            "error_code": "BRIDGE_DISPATCH_FAILED",
            "action": action,
            "error_type": type(exc).__name__,
        }

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
