"""
JAYA Dynamic Feature: Dashboard
Generated by FeatureCompiler v0.1
Feature ID: b0ebe034
Description: Main dashboard with metrics and quick actions

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "dashboard"
FEATURE_ID = "b0ebe034"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Main dashboard with metrics and quick actions"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from src.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from src.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_b0ebe034() -> WidgetBase:
    """Build the "Dashboard" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="8a3f231b-4b7e-4786-b115-8324a0c9f4f8",
        label="Untitled",
        layout="flex_col",
        rect={"x": {"value": 0, "unit": "px"}, "y": {"value": 0, "unit": "px"}, "width": {"value": 1200.0, "unit": "px"}, "height": {"value": 800.0, "unit": "px"}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: 2eb508b6
    w_2eb508b6 = PanelWidget(
        widget_id="2eb508b6-ee19-4ecf-b881-c78f9d49140a",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    root.add_child(w_2eb508b6)
    # Children of w_2eb508b6
    # label: Untitled
    w_de225289 = LabelWidget(
        widget_id="de225289-d7f2-433b-bf08-8e7c0a150ef2",
        label="Untitled",
        visible=True,
        enabled=True,
    )
    w_2eb508b6.add_child(w_de225289)
    # panel: 749c9a68
    w_749c9a68 = PanelWidget(
        widget_id="749c9a68-d433-4b8d-9b42-61d3859d2d3f",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_2eb508b6.add_child(w_749c9a68)
    # Children of w_749c9a68
    # button: New Task
    w_99202324 = ButtonWidget(
        widget_id="99202324-58e8-4bc2-8229-d1588190e895",
        label="New Task",
        visible=True,
        enabled=True,
        metadata={"variant": "primary"},
    )
    w_749c9a68.add_child(w_99202324)
    # Event handlers for w_99202324
    w_99202324.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))
    # button: Settings
    w_c9c1ee5c = ButtonWidget(
        widget_id="c9c1ee5c-3eae-41e1-8d00-9ccb7ed92706",
        label="Settings",
        visible=True,
        enabled=True,
        metadata={"variant": "secondary"},
    )
    w_749c9a68.add_child(w_c9c1ee5c)
    # Event handlers for w_c9c1ee5c
    w_c9c1ee5c.on("click", lambda d, a="jaya:open_dialog", p={}: jaya_dispatch(a, p))
    # panel: bfec629b
    w_bfec629b = PanelWidget(
        widget_id="bfec629b-7b52-481e-be1a-de4af6494b2f",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_bfec629b)
    # Children of w_bfec629b
    # panel: 4ec65272
    w_4ec65272 = PanelWidget(
        widget_id="4ec65272-713a-4a38-bca3-7dfd03c90985",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_bfec629b.add_child(w_4ec65272)
    # Children of w_4ec65272
    # panel: 97bb2f0e
    w_97bb2f0e = PanelWidget(
        widget_id="97bb2f0e-fe12-49b7-b7ba-e6e9d1ef4c10",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_4ec65272.add_child(w_97bb2f0e)
    # Children of w_97bb2f0e
    # label: Total Tasks
    w_d1634e58 = LabelWidget(
        widget_id="d1634e58-f2b5-4aa6-8942-1f09f6385404",
        label="Total Tasks",
        visible=True,
        enabled=True,
    )
    w_97bb2f0e.add_child(w_d1634e58)
    # label: 1,234
    w_dccc4b47 = LabelWidget(
        widget_id="dccc4b47-632b-4568-a5a4-84d0a0d471ad",
        label="1,234",
        visible=True,
        enabled=True,
    )
    w_97bb2f0e.add_child(w_dccc4b47)
    # label: +12%
    w_2a35a7d5 = LabelWidget(
        widget_id="2a35a7d5-48e9-4b83-ad79-e0e105716492",
        label="+12%",
        visible=True,
        enabled=True,
    )
    w_97bb2f0e.add_child(w_2a35a7d5)
    # panel: f152cfad
    w_f152cfad = PanelWidget(
        widget_id="f152cfad-fd4f-4716-bf89-3995c9f78429",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_4ec65272.add_child(w_f152cfad)
    # Children of w_f152cfad
    # label: Completed
    w_d251a2d2 = LabelWidget(
        widget_id="d251a2d2-6bf8-4e85-89b7-fcda040f847d",
        label="Completed",
        visible=True,
        enabled=True,
    )
    w_f152cfad.add_child(w_d251a2d2)
    # label: 987
    w_b5748054 = LabelWidget(
        widget_id="b5748054-db3e-4ec5-9723-079c335a71d5",
        label="987",
        visible=True,
        enabled=True,
    )
    w_f152cfad.add_child(w_b5748054)
    # label: +8%
    w_0cccc5ff = LabelWidget(
        widget_id="0cccc5ff-570b-4fe4-9dbd-1e140ba7a8f7",
        label="+8%",
        visible=True,
        enabled=True,
    )
    w_f152cfad.add_child(w_0cccc5ff)
    # panel: 6d7ab13d
    w_6d7ab13d = PanelWidget(
        widget_id="6d7ab13d-043b-4b92-b2d6-25242b1f0c7c",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_4ec65272.add_child(w_6d7ab13d)
    # Children of w_6d7ab13d
    # label: In Progress
    w_ea15b43d = LabelWidget(
        widget_id="ea15b43d-f0c9-451b-bd07-32aadee2771d",
        label="In Progress",
        visible=True,
        enabled=True,
    )
    w_6d7ab13d.add_child(w_ea15b43d)
    # label: 156
    w_263e60a4 = LabelWidget(
        widget_id="263e60a4-4f7c-47c4-982d-b64e322103c9",
        label="156",
        visible=True,
        enabled=True,
    )
    w_6d7ab13d.add_child(w_263e60a4)
    # label: -3%
    w_1daee32e = LabelWidget(
        widget_id="1daee32e-5cd1-41d5-b013-6eb6b366f2eb",
        label="-3%",
        visible=True,
        enabled=True,
    )
    w_6d7ab13d.add_child(w_1daee32e)
    # panel: 05c0abfe
    w_05c0abfe = PanelWidget(
        widget_id="05c0abfe-aa9a-43b7-9938-ec64e1f3f504",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_4ec65272.add_child(w_05c0abfe)
    # Children of w_05c0abfe
    # label: Overdue
    w_be79e46d = LabelWidget(
        widget_id="be79e46d-e7ab-4573-8b67-e901e3cdcf74",
        label="Overdue",
        visible=True,
        enabled=True,
    )
    w_05c0abfe.add_child(w_be79e46d)
    # label: 12
    w_e96b5241 = LabelWidget(
        widget_id="e96b5241-a540-4a4e-b15d-280d3ff557d8",
        label="12",
        visible=True,
        enabled=True,
    )
    w_05c0abfe.add_child(w_e96b5241)
    # label: +2%
    w_7507bf8b = LabelWidget(
        widget_id="7507bf8b-5ad3-4124-8ab8-f2ee018d66ea",
        label="+2%",
        visible=True,
        enabled=True,
    )
    w_05c0abfe.add_child(w_7507bf8b)

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.
    
    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict
        
    Returns:
        Result dict with status and any output data
    """
    config = config or {}
    
    # Build scene
    root = build_scene_b0ebe034()
    
    # Initialize runtime
    from src.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="b0ebe034",
        feature_name="dashboard",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )
    
    # Set global runtime reference for dispatch
    set_runtime(runtime)
    
    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))
    
    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "dashboard"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.
    
    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action
        
    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}
    
    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        print(f"Warning: No JAYA bridge set, action {action} dropped")
        return None
    
    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as e:
        print(f"JAYA dispatch error: {e}")
        return None

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
