"""Phase 3A — Feature Compiler for Dynamic UI Generation.

This module compiles SceneGraph UI specifications into runnable Python modules
that can be executed in the os_kernel sandbox.

The compiler generates:
1. A feature module with a standard entry point
2. Widget class implementations
3. Event handling and state management
4. JAYA action dispatchers
"""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path
from typing import Any, Dict, Set

from src.os_kernel.ui_spec import (
    LayoutType,
    SceneGraph,
    StyleTokens,
    WidgetSpec,
    WidgetType,
)


class FeatureCompiler:
    """Compiles SceneGraph UI specs into runnable feature modules."""

    def __init__(self, target_version: str = "0.1"):
        self.target_version = target_version
        self._widget_registry: Dict[WidgetType, str] = self._build_widget_registry()
        self._imports: Set[str] = set()

    def _build_widget_registry(self) -> Dict[WidgetType, str]:
        """Map widget types to their implementation class names."""
        return {
            WidgetType.WINDOW: "WindowWidget",
            WidgetType.PANEL: "PanelWidget",
            WidgetType.BUTTON: "ButtonWidget",
            WidgetType.LABEL: "LabelWidget",
            WidgetType.TEXT_INPUT: "TextInputWidget",
            WidgetType.TEXTAREA: "TextAreaWidget",
            WidgetType.SELECT: "SelectWidget",
            WidgetType.CHECKBOX: "CheckboxWidget",
            WidgetType.RADIO_GROUP: "RadioGroupWidget",
            WidgetType.SLIDER: "SliderWidget",
            WidgetType.PROGRESS_BAR: "ProgressBarWidget",
            WidgetType.TABLE: "TableWidget",
            WidgetType.LIST: "ListWidget",
            WidgetType.TREE: "TreeWidget",
            WidgetType.TAB_VIEW: "TabViewWidget",
            WidgetType.SPLIT_VIEW: "SplitViewWidget",
            WidgetType.CHART: "ChartWidget",
            WidgetType.CANVAS: "CanvasWidget",
            WidgetType.IMAGE: "ImageWidget",
            WidgetType.ICON: "IconWidget",
            WidgetType.TOOLBAR: "ToolbarWidget",
            WidgetType.MENU_BAR: "MenuBarWidget",
            WidgetType.STATUS_BAR: "StatusBarWidget",
            WidgetType.DIALOG: "DialogWidget",
            WidgetType.SIDEBAR: "SidebarWidget",
            WidgetType.HEADER: "HeaderWidget",
            WidgetType.FOOTER: "FooterWidget",
            WidgetType.FORM: "FormWidget",
            WidgetType.GRID: "GridWidget",
            WidgetType.FLEX: "FlexWidget",
            WidgetType.SCROLL_VIEW: "ScrollViewWidget",
            WidgetType.CUSTOM: "CustomWidget",
        }

    def compile(self, scene: SceneGraph, feature_name: str = None) -> str:
        """Compile a SceneGraph into a Python feature module."""
        feature_name = feature_name or scene.name.replace(" ", "_").lower()
        feature_id = scene.id
        feature_symbol_id = scene.id[:8]

        # Collect all widget types used
        used_widgets = self._collect_widget_types(scene.root)

        # Generate the module
        module_parts = [
            self._generate_header(feature_name, feature_id, scene),
            self._generate_imports(used_widgets),
            self._generate_style_tokens(scene.styles),
            self._generate_widget_classes(used_widgets),
            self._generate_scene_builder(scene),
            self._generate_feature_entry_point(
                feature_name,
                feature_id,
                feature_symbol_id,
            ),
            self._generate_jaya_dispatcher(),
        ]

        return "\n\n".join(module_parts)

    def _collect_widget_types(self, widget: WidgetSpec) -> Set[WidgetType]:
        """Collect all widget types used in the scene."""
        types = {widget.type}
        for child in widget.children:
            types.update(self._collect_widget_types(child))
        return types

    @staticmethod
    def _python_literal(value: Any) -> str:
        """Render JSON-compatible data as valid deterministic Python syntax."""
        try:
            normalized = json.loads(json.dumps(value))
        except (TypeError, ValueError) as exc:
            raise ValueError(
                f"Feature value is not JSON-compatible ({type(value).__name__})"
            ) from exc
        return repr(normalized)

    def _generate_header(self, feature_name: str, feature_id: str, scene: SceneGraph) -> str:
        return f'''"""
JAYA Dynamic Feature: {scene.name}
Generated by FeatureCompiler v{self.target_version}
Feature ID: {feature_id}
Description: {scene.description}

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "{feature_name}"
FEATURE_ID = "{feature_id}"
FEATURE_VERSION = "{scene.metadata.get('version', '0.1.0')}"
FEATURE_DESCRIPTION = """{scene.description}"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"
'''

    def _generate_imports(self, used_widgets: Set[WidgetType]) -> str:
        imports = [
            "import asyncio",
            "import json",
            "import uuid",
            "from dataclasses import dataclass, field",
            "from typing import Any, Callable, Dict, List, Optional, Set",
            "from abc import ABC, abstractmethod",
            "",
            "# JAYA runtime imports",
            "try:",
            "    from src.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus",
            "    from src.os_kernel.feature_bridge import JayaBridge",
            "except ImportError:",
            "    # Fallback for standalone testing",
            "    FeatureRuntime = object",
            "    WidgetBase = object",
            "    EventBus = object",
            "    JayaBridge = object",
        ]

        # Add widget-specific imports
        if WidgetType.CHART in used_widgets:
            imports.append("try: import matplotlib.pyplot as plt\nexcept: plt = None")
        if WidgetType.CANVAS in used_widgets:
            imports.append("try: from PIL import Image, ImageDraw\nexcept: Image = ImageDraw = None")

        return "\n".join(imports)

    def _generate_style_tokens(self, styles: StyleTokens) -> str:
        css_vars = styles.to_css_vars()
        var_lines = [f'    "{k}": "{v}",' for k, v in css_vars.items()]
        return f'''# Design System Tokens
STYLE_TOKENS = {{
{chr(10).join(var_lines)}
}}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)
'''

    def _generate_widget_classes(self, used_widgets: Set[WidgetType]) -> str:
        classes = [
            "# Base Widget Class",
            self._generate_base_widget_class(),
            "",
            "# Widget Implementations",
        ]

        for widget_type in sorted(used_widgets, key=lambda w: w.value):
            class_name = self._widget_registry[widget_type]
            classes.append(self._generate_widget_class(widget_type, class_name))

        return "\n\n".join(classes)

    def _generate_base_widget_class(self) -> str:
        return '''class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass
'''

    def _generate_widget_class(self, widget_type: WidgetType, class_name: str) -> str:
        """Generate a widget class for the given type."""
        base_methods = self._get_widget_methods(widget_type)

        return f'''class {class_name}(WidgetBase):
    """{widget_type.value.replace('_', ' ').title()} widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="{widget_type.value}", **kwargs)
        {base_methods.get("init", "pass")}

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        {base_methods.get("handle_action", "return None")}

    {base_methods.get("extra_methods", "")}
'''

    def _get_widget_methods(self, widget_type: WidgetType) -> Dict[str, str]:
        """Get widget-type-specific method implementations."""
        methods = {
            WidgetType.BUTTON: {
                "init": "self._value = kwargs.get('value', False)",
                "handle_action": "if action == \"click\":\n            self._value = not self._value\n            self.emit(\"click\", {\"value\": self._value})\n            return {\"clicked\": True, \"value\": self._value}\n        return None",
            },
            WidgetType.TEXT_INPUT: {
                "init": "self._value = kwargs.get('value', '')\n        self.placeholder = kwargs.get('placeholder', '')",
                "handle_action": "if action == \"set_value\":\n            self._value = payload.get(\"value\", \"\")\n            self.emit(\"change\", {\"value\": self._value})\n            return {\"value\": self._value}\n        elif action == \"get_value\":\n            return {\"value\": self._value}\n        elif action == \"focus\":\n            self.emit(\"focus\", {})\n            return {\"focused\": True}\n        return None",
            },
            WidgetType.LABEL: {
                "init": "pass",
                "handle_action": "if action == \"set_text\":\n            self.label = payload.get(\"text\", \"\")\n            return {\"text\": self.label}\n        return None",
            },
            WidgetType.PANEL: {
                "init": "self.layout = kwargs.get('layout', 'flex_col')",
                "handle_action": "if action == \"add_child\":\n            # Child addition handled at runtime\n            return {\"added\": True}\n        elif action == \"remove_child\":\n            return {\"removed\": True}\n        return None",
            },
            WidgetType.WINDOW: {
                "init": "self.title = kwargs.get('label', 'Window')\n        self.minimized = False\n        self.maximized = False",
                "handle_action": "if action == \"minimize\":\n            self.minimized = True\n            return {\"minimized\": True}\n        elif action == \"maximize\":\n            self.maximized = not self.maximized\n            return {\"maximized\": self.maximized}\n        elif action == \"close\":\n            self.emit(\"close\", {})\n            return {\"closed\": True}\n        elif action == \"set_title\":\n            self.title = payload.get(\"title\", \"\")\n            return {\"title\": self.title}\n        return None",
            },
            WidgetType.TABLE: {
                "init": "self.columns = kwargs.get('metadata', {}).get('columns', [])\n        self.data = kwargs.get('metadata', {}).get('data', [])",
                "handle_action": "if action == \"set_data\":\n            self.data = payload.get(\"data\", [])\n            self.emit(\"data_change\", {\"count\": len(self.data)})\n            return {\"rows\": len(self.data)}\n        elif action == \"get_data\":\n            return {\"data\": self.data}\n        elif action == \"add_row\":\n            row = payload.get(\"row\", {})\n            self.data.append(row)\n            return {\"added\": True, \"index\": len(self.data) - 1}\n        return None",
            },
            WidgetType.LIST: {
                "init": "self.items = kwargs.get('metadata', {}).get('items', [])",
                "handle_action": "if action == \"set_items\":\n            self.items = payload.get(\"items\", [])\n            return {\"count\": len(self.items)}\n        elif action == \"add_item\":\n            item = payload.get(\"item\")\n            self.items.append(item)\n            return {\"added\": True}\n        return None",
            },
            WidgetType.PROGRESS_BAR: {
                "init": "self._value = kwargs.get('value', 0)\n        self.max_value = kwargs.get('metadata', {}).get('max', 100)",
                "handle_action": "if action == \"set_progress\":\n            self._value = max(0, min(self.max_value, payload.get(\"value\", 0)))\n            self.emit(\"progress\", {\"value\": self._value, \"max\": self.max_value})\n            return {\"value\": self._value, \"percent\": self._value / self.max_value * 100}\n        return None",
            },
            WidgetType.SELECT: {
                "init": "self.options = kwargs.get('options', [])\n        self._value = kwargs.get('value')",
                "handle_action": "if action == \"set_options\":\n            self.options = payload.get(\"options\", [])\n            return {\"options\": self.options}\n        elif action == \"set_value\":\n            self._value = payload.get(\"value\")\n            self.emit(\"change\", {\"value\": self._value})\n            return {\"value\": self._value}\n        return None",
            },
        }

        return methods.get(widget_type, {"init": "pass", "handle_action": "return None"})

    def _generate_scene_builder(self, scene: SceneGraph) -> str:
        """Generate the scene builder function."""
        builder = [
            f"def build_scene_{scene.id[:8]}() -> WidgetBase:",
            f'    """Build the "{scene.name}" scene graph."""',
            "    # Global state",
            f"    global_state = {json.dumps(scene.global_state, indent=4)}",
            "",
            "    # Create root widget",
            f"    root = {self._widget_registry[scene.root.type]}(",
        ]

        # Root widget properties
        root_props = self._widget_props_to_kwargs(scene.root)
        for k, v in root_props.items():
            builder.append(f"        {k}={v},")
        builder.append("    )")

        # Build children recursively
        builder.append("")
        builder.append("    # Build child hierarchy")
        for child in scene.root.children:
            builder.append(self._generate_widget_creation(child, "root", 1))

        builder.append("")
        builder.append("    # Apply global bindings")
        builder.append("    def apply_all_bindings(widget):")
        builder.append("        widget.apply_bindings(global_state)")
        builder.append("        for child in widget.children:")
        builder.append("            apply_all_bindings(child)")
        builder.append("    apply_all_bindings(root)")

        builder.append("")
        builder.append("    return root")

        return "\n".join(builder)

    def _generate_widget_creation(self, widget: WidgetSpec, parent_var: str, indent: int) -> str:
        """Generate code to create a widget and attach to parent."""
        indent_str = "    " * indent
        var_name = f"w_{widget.id[:8]}"

        lines = [
            f"{indent_str}# {widget.type.value}: {widget.label or widget.id[:8]}",
            f"{indent_str}{var_name} = {self._widget_registry[widget.type]}(",
        ]

        props = self._widget_props_to_kwargs(widget)
        for k, v in props.items():
            lines.append(f"{indent_str}    {k}={v},")
        lines.append(f"{indent_str})")

        lines.append(f"{indent_str}{parent_var}.add_child({var_name})")

        # Children - use SAME indent level (flat structure)
        if widget.children:
            lines.append(f"{indent_str}# Children of {var_name}")
            for child in widget.children:
                lines.append(self._generate_widget_creation(child, var_name, indent))

        # Event handlers
        if widget.events:
            lines.append(f"{indent_str}# Event handlers for {var_name}")
            for event in widget.events:
                action = event.action
                payload = self._python_literal(event.payload)
                lines.append(f'{indent_str}{var_name}.on("{event.event}", lambda d, a="{action}", p={payload}: jaya_dispatch(a, p))')

        # Bindings
        if widget.bindings:
            binding_specs = [asdict(binding) for binding in widget.bindings]
            lines.append(
                f"{indent_str}{var_name}.bindings = "
                f"{self._python_literal(binding_specs)}"
            )

        return "\n".join(lines)

    def _widget_props_to_kwargs(self, widget: WidgetSpec) -> Dict[str, str]:
        """Convert widget properties to constructor kwargs."""
        props = {
            "widget_id": f'"{widget.id}"',
            "label": f'"{widget.label}"',
        }

        if widget.style.to_css():
            style_dict = widget.style.to_css()
            props["style"] = self._python_literal(style_dict)

        if widget.layout:
            props["layout"] = f'"{widget.layout.value}"'

        if widget.rect:
            rect_dict = asdict(widget.rect)
            # Convert Dimension objects to serializable form
            for k, v in rect_dict.items():
                if hasattr(v, 'value') and hasattr(v, 'unit'):
                    rect_dict[k] = {"value": v.value, "unit": v.unit.value}
            props["rect"] = self._python_literal(rect_dict)

        props["visible"] = str(widget.visible)
        props["enabled"] = str(widget.enabled)

        if widget.metadata:
            props["metadata"] = self._python_literal(widget.metadata)

        if widget.type in (WidgetType.TEXT_INPUT, WidgetType.TEXTAREA, WidgetType.SELECT):
            props["value"] = (
                self._python_literal(widget.value)
                if widget.value is not None
                else '""'
            )

        if widget.type == WidgetType.SELECT:
            props["options"] = self._python_literal(widget.options)

        if widget.placeholder:
            props["placeholder"] = f'"{widget.placeholder}"'

        return props

    def _generate_feature_entry_point(
        self,
        feature_name: str,
        feature_id: str,
        feature_symbol_id: str,
    ) -> str:
        return f'''# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.

    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict

    Returns:
        Result dict with status and any output data
    """
    config = config or {{}}

    # Build scene
    root = build_scene_{feature_symbol_id}()

    # Initialize runtime
    from src.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="{feature_id}",
        feature_name="{feature_name}",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )

    # Set global runtime reference for dispatch
    set_runtime(runtime)

    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))

    # Run feature lifecycle
    try:
        await runtime.run()
        return {{"status": "completed", "feature": "{feature_name}"}}
    except Exception as e:
        return {{"status": "error", "error": str(e)}}
    finally:
        await runtime.unmount()

def feature_manifest() -> Dict[str, Any]:
    """Return the generated feature's registration contract."""
    return {{
        "name": FEATURE_NAME,
        "id": FEATURE_ID,
        "version": FEATURE_VERSION,
        "description": FEATURE_DESCRIPTION,
        "protocol_version": FEATURE_PROTOCOL_VERSION,
        "entry_point": "run_feature",
        "capabilities": ["ui", "events", "state", "jaya_actions"],
        "permissions": ["ui_mount", "state_read", "state_write", "api_call"],
    }}

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.

    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action

    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {{"error": "Feature not running"}}

    return _runtime.dispatch(action, payload or {{}})
'''

    def _generate_jaya_dispatcher(self) -> str:
        return '''# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        return {
            "success": False,
            "error_code": "BRIDGE_UNAVAILABLE",
            "action": action,
        }

    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as exc:
        return {
            "success": False,
            "error_code": "BRIDGE_DISPATCH_FAILED",
            "action": action,
            "error_type": type(exc).__name__,
        }

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
'''

    def save_feature(self, scene: SceneGraph, output_dir: str, feature_name: str = None) -> Path:
        """Compile and save feature to directory."""
        feature_name = feature_name or scene.name.replace(" ", "_").lower()
        output_path = Path(output_dir) / feature_name
        output_path.mkdir(parents=True, exist_ok=True)

        # Generate feature module
        module_code = self.compile(scene, feature_name)
        module_file = output_path / f"{feature_name}.py"
        module_file.write_text(module_code, encoding="utf-8")

        # Save scene graph as JSON for reference
        scene_file = output_path / "scene.json"
        scene_fs.write_text(scene.to_json(), encoding="utf-8")

        # Generate __init__.py for package
        init_file = output_path / "__init__.py"
        init_fs.write_text(f'''"""
{scene.name} - JAYA Dynamic Feature
Auto-generated by FeatureCompiler v{self.target_version}
"""
from .{feature_name} import run_feature, feature_manifest, set_jaya_bridge, jaya_dispatch

__all__ = ["run_feature", "feature_manifest", "set_jaya_bridge", "jaya_dispatch"]
''', encoding="utf-8")

        # Generate manifest.json for feature registry
        manifest = {
            "version": scene.metadata.get("version", "0.1.0"),
            "id": scene.id,
            "name": scene.name,
            "description": scene.description,
            "protocol_version": "1.0",
            "entry_point": f"{feature_name}.run_feature",
            "capabilities": scene.metadata.get("capabilities", ["ui", "events", "state", "jaya_actions"]),
            "permissions": scene.metadata.get("permissions", ["ui_mount", "state_read", "state_write", "api_call"]),
            "dependencies": scene.metadata.get("dependencies", {}),
            "metadata": scene.metadata,
        }
        manifest_file = output_path / "manifest.json"
        manifest_fs.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

        return output_path


def compile_scene_to_feature(
    scene: SceneGraph,
    output_dir: str,
    feature_name: str = None,
) -> Path:
    """Convenience function to compile a scene to a feature."""
    compiler = FeatureCompiler()
    return compiler.save_feature(scene, output_dir, feature_name)


# Example usage and testing
if __name__ == "__main__":
    from src.os_kernel.ui_spec import (
        LayoutType,
        SceneGraph,
        StyleTokens,
        WidgetSpec,
        WidgetType,
        create_button,
        create_label,
        create_panel,
        create_text_input,
        create_window,
    )

    # Create a sample scene: simple login dialog
    scene = SceneGraph(
        name="Login Dialog",
        description="A simple login form for JAYA authentication",
        root=create_window(
            title="JAYA Login",
            width="400px",
            height="300px",
            children=[
                create_panel(
                    layout=LayoutType.FLEX_COL,
                    children=[
                        create_label("Welcome to JAYA"),
                        create_text_input(
                            placeholder="Username",
                            value="",
                            on_change="jaya:update_state",
                        ),
                        create_text_input(
                            placeholder="Password",
                            value="",
                            on_change="jaya:update_state",
                        ),
                        create_button(
                            label="Login",
                            on_click="jaya:run_task",
                        ),
                    ],
                ),
            ],
        ),
    )

    # Compile
    compiler = FeatureCompiler()
    output = compiler.save_feature(scene, "./test_features", "login_dialog")
    print(f"Feature compiled to: {output}")
    print(f"Module: {output / 'login_dialog.py'}")
