package com.example.jaya.skills

class DocumentSkill : AiSkill {
    override val name: String = "Document Creator"
    override val description: String = "Creates text documents based on user requests"

    override fun matches(input: String): Boolean {
        return input.contains("buat dokumen", ignoreCase = true) || 
               input.contains("create document", ignoreCase = true)
    }

    override suspend fun execute(input: String, sessionId: Long): SkillResult {
        val fileName = "doc_${System.currentTimeMillis()}.txt"
        val content = "Analysis for: $input\n\nGenerated by Jaya AI Blueprint Skills Engine."
        
        return SkillResult(
            content = "Saya telah menjalankan skill 'Document Creator'. Dokumen '$fileName' telah berhasil dibuat dan disimpan.",
            attachedFileContent = content,
            attachedFileName = fileName
        )
    }
}
