"""
JAYA Dynamic Feature: Settings
Generated by FeatureCompiler v0.1
Feature ID: b14c835d-1313-4301-85da-585d8bd9a9e0
Description: Application settings and preferences

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "settings_dialog"
FEATURE_ID = "b14c835d-1313-4301-85da-585d8bd9a9e0"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Application settings and preferences"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from src.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from src.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class TextInputWidget(WidgetBase):
    """Text Input widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="text_input", **kwargs)
        self._value = kwargs.get('value', '')
        self.placeholder = kwargs.get('placeholder', '')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_value":
            self._value = payload.get("value", "")
            self.emit("change", {"value": self._value})
            return {"value": self._value}
        elif action == "get_value":
            return {"value": self._value}
        elif action == "focus":
            self.emit("focus", {})
            return {"focused": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_b14c835d() -> WidgetBase:
    """Build the "Settings" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="7a0567c2-3a61-405e-b800-2a3fececcfba",
        label="Untitled",
        layout="flex_col",
        rect={"x": {"value": 0, "unit": "px"}, "y": {"value": 0, "unit": "px"}, "width": {"value": 600.0, "unit": "px"}, "height": {"value": 700.0, "unit": "px"}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: ff3b03f4
    w_ff3b03f4 = PanelWidget(
        widget_id="ff3b03f4-a5f8-4045-b14f-986b2521349c",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_ff3b03f4)
    # Children of w_ff3b03f4
    # label: Untitled
    w_0826e9a9 = LabelWidget(
        widget_id="0826e9a9-a8a1-4546-b297-78fa94c390d0",
        label="Untitled",
        visible=True,
        enabled=True,
    )
    w_ff3b03f4.add_child(w_0826e9a9)
    # panel: 616c672c
    w_616c672c = PanelWidget(
        widget_id="616c672c-0002-4ce1-8877-61a2e7a2569f",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_ff3b03f4.add_child(w_616c672c)
    # Children of w_616c672c
    # label: General
    w_78fac35d = LabelWidget(
        widget_id="78fac35d-92ad-4550-9fee-1119bd104b8e",
        label="General",
        visible=True,
        enabled=True,
    )
    w_616c672c.add_child(w_78fac35d)
    # text_input: 5dc5cd13
    w_5dc5cd13 = TextInputWidget(
        widget_id="5dc5cd13-03e0-458c-9e54-cca923e1d06a",
        label="",
        visible=True,
        enabled=True,
        value="",
        placeholder="Your name",
    )
    w_616c672c.add_child(w_5dc5cd13)
    # label: Select: Language
    w_31ff6f15 = LabelWidget(
        widget_id="31ff6f15-2d40-4ade-adf9-263bb85f206c",
        label="Select: Language",
        visible=True,
        enabled=True,
    )
    w_616c672c.add_child(w_31ff6f15)
    # label: Select: Theme
    w_d1c9d07e = LabelWidget(
        widget_id="d1c9d07e-dcae-4f97-b24a-5d3337573678",
        label="Select: Theme",
        visible=True,
        enabled=True,
    )
    w_616c672c.add_child(w_d1c9d07e)
    # panel: 535c531e
    w_535c531e = PanelWidget(
        widget_id="535c531e-89fc-4a61-ae34-b12ede06f2c8",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_ff3b03f4.add_child(w_535c531e)
    # Children of w_535c531e
    # label: Privacy & Security
    w_abf3910b = LabelWidget(
        widget_id="abf3910b-e9f4-4a8f-8eb0-bb612e0a61a7",
        label="Privacy & Security",
        visible=True,
        enabled=True,
    )
    w_535c531e.add_child(w_abf3910b)
    # label: Checkbox: Allow anonymous usage analytics
    w_f8567a5d = LabelWidget(
        widget_id="f8567a5d-d1c5-46ee-8ed9-0fcde75dc0d0",
        label="Checkbox: Allow anonymous usage analytics",
        visible=True,
        enabled=True,
    )
    w_535c531e.add_child(w_f8567a5d)
    # label: Checkbox: Crash reporting
    w_eacac8f7 = LabelWidget(
        widget_id="eacac8f7-4c07-4357-9637-24ddc751e6fb",
        label="Checkbox: Crash reporting",
        visible=True,
        enabled=True,
    )
    w_535c531e.add_child(w_eacac8f7)
    # label: Checkbox: Auto-update
    w_2b04b3c0 = LabelWidget(
        widget_id="2b04b3c0-3c74-4a58-b43c-defa043adfc6",
        label="Checkbox: Auto-update",
        visible=True,
        enabled=True,
    )
    w_535c531e.add_child(w_2b04b3c0)
    # panel: 673e27ae
    w_673e27ae = PanelWidget(
        widget_id="673e27ae-9702-41de-b98f-ad817900657e",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_ff3b03f4.add_child(w_673e27ae)
    # Children of w_673e27ae
    # label: Notifications
    w_80362923 = LabelWidget(
        widget_id="80362923-3bb3-4aeb-85da-6cd111527e7e",
        label="Notifications",
        visible=True,
        enabled=True,
    )
    w_673e27ae.add_child(w_80362923)
    # label: Checkbox: Email notifications
    w_1005b497 = LabelWidget(
        widget_id="1005b497-c473-45b9-bbfe-bca532f7279c",
        label="Checkbox: Email notifications",
        visible=True,
        enabled=True,
    )
    w_673e27ae.add_child(w_1005b497)
    # label: Checkbox: Push notifications
    w_e9178a95 = LabelWidget(
        widget_id="e9178a95-ebd4-4217-b062-76c12d9a378d",
        label="Checkbox: Push notifications",
        visible=True,
        enabled=True,
    )
    w_673e27ae.add_child(w_e9178a95)
    # label: Select: Frequency
    w_ee437907 = LabelWidget(
        widget_id="ee437907-8211-4770-a9c2-a721bc412fcb",
        label="Select: Frequency",
        visible=True,
        enabled=True,
    )
    w_673e27ae.add_child(w_ee437907)
    # panel: bf1e81f0
    w_bf1e81f0 = PanelWidget(
        widget_id="bf1e81f0-8a3c-4349-ab09-53e1d032fab2",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_ff3b03f4.add_child(w_bf1e81f0)
    # Children of w_bf1e81f0
    # button: Cancel
    w_3f65ef0b = ButtonWidget(
        widget_id="3f65ef0b-5cb5-48ad-a9f7-e261e55645e7",
        label="Cancel",
        visible=True,
        enabled=True,
        metadata={"variant": "secondary"},
    )
    w_bf1e81f0.add_child(w_3f65ef0b)
    # Event handlers for w_3f65ef0b
    w_3f65ef0b.on("click", lambda d, a="jaya:close_dialog", p={}: jaya_dispatch(a, p))
    # button: Save Changes
    w_3e6e8143 = ButtonWidget(
        widget_id="3e6e8143-e5ce-49c2-9fa1-0faa1ea77867",
        label="Save Changes",
        visible=True,
        enabled=True,
        metadata={"variant": "primary"},
    )
    w_bf1e81f0.add_child(w_3e6e8143)
    # Event handlers for w_3e6e8143
    w_3e6e8143.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.

    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict

    Returns:
        Result dict with status and any output data
    """
    config = config or {}

    # Build scene
    root = build_scene_b14c835d()

    # Initialize runtime
    from src.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="b14c835d-1313-4301-85da-585d8bd9a9e0",
        feature_name="settings_dialog",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )

    # Set global runtime reference for dispatch
    set_runtime(runtime)

    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))

    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "settings_dialog"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

def feature_manifest() -> Dict[str, Any]:
    """Return the generated feature's registration contract."""
    return {
        "name": FEATURE_NAME,
        "id": FEATURE_ID,
        "version": FEATURE_VERSION,
        "description": FEATURE_DESCRIPTION,
        "protocol_version": FEATURE_PROTOCOL_VERSION,
        "entry_point": "run_feature",
        "capabilities": ["ui", "events", "state", "jaya_actions"],
        "permissions": ["ui_mount", "state_read", "state_write", "api_call"],
    }

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.

    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action

    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}

    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        print(f"Warning: No JAYA bridge set, action {action} dropped")
        return None

    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as e:
        print(f"JAYA dispatch error: {e}")
        return None

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
