"""
JAYA Dynamic Feature: Settings
Generated by FeatureCompiler v0.1
Feature ID: b38e87e4
Description: Application settings and preferences

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "settings_dialog"
FEATURE_ID = "b38e87e4-be23-495c-b02d-927d28e41c5f"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Application settings and preferences"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from jaya_core.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from jaya_core.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class TextInputWidget(WidgetBase):
    """Text Input widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="text_input", **kwargs)
        self._value = kwargs.get('value', '')
        self.placeholder = kwargs.get('placeholder', '')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_value":
            self._value = payload.get("value", "")
            self.emit("change", {"value": self._value})
            return {"value": self._value}
        elif action == "get_value":
            return {"value": self._value}
        elif action == "focus":
            self.emit("focus", {})
            return {"focused": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_b38e87e4() -> WidgetBase:
    """Build the "Settings" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="1b152baa-48ac-4f4c-828f-de83aa360da0",
        label="Untitled",
        layout="flex_col",
        rect={"x": {"value": 0, "unit": "px"}, "y": {"value": 0, "unit": "px"}, "width": {"value": 600.0, "unit": "px"}, "height": {"value": 700.0, "unit": "px"}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: dcfc1d9d
    w_dcfc1d9d = PanelWidget(
        widget_id="dcfc1d9d-044c-46dd-9c06-be8bdd4fec0b",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_dcfc1d9d)
    # Children of w_dcfc1d9d
    # label: Untitled
    w_c8ca8005 = LabelWidget(
        widget_id="c8ca8005-6c01-4926-9649-59145115453f",
        label="Untitled",
        visible=True,
        enabled=True,
    )
    w_dcfc1d9d.add_child(w_c8ca8005)
    # panel: 2e85e42b
    w_2e85e42b = PanelWidget(
        widget_id="2e85e42b-f6ca-4ee9-b008-7ca259c756e6",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_dcfc1d9d.add_child(w_2e85e42b)
    # Children of w_2e85e42b
    # label: General
    w_cd5feaac = LabelWidget(
        widget_id="cd5feaac-230c-461a-96b7-efed3b09c771",
        label="General",
        visible=True,
        enabled=True,
    )
    w_2e85e42b.add_child(w_cd5feaac)
    # text_input: cc5c71f3
    w_cc5c71f3 = TextInputWidget(
        widget_id="cc5c71f3-87c5-4fbf-ad28-747267984359",
        label="",
        visible=True,
        enabled=True,
        value="",
        placeholder="Your name",
    )
    w_2e85e42b.add_child(w_cc5c71f3)
    # label: Select: Language
    w_520b8f87 = LabelWidget(
        widget_id="520b8f87-8bb7-438f-acf0-978396e602d5",
        label="Select: Language",
        visible=True,
        enabled=True,
    )
    w_2e85e42b.add_child(w_520b8f87)
    # label: Select: Theme
    w_ffaeda8d = LabelWidget(
        widget_id="ffaeda8d-250d-42d5-8907-2c52e0dd3363",
        label="Select: Theme",
        visible=True,
        enabled=True,
    )
    w_2e85e42b.add_child(w_ffaeda8d)
    # panel: 95bf8922
    w_95bf8922 = PanelWidget(
        widget_id="95bf8922-b60f-4fba-920b-8d7322f0dcff",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_dcfc1d9d.add_child(w_95bf8922)
    # Children of w_95bf8922
    # label: Privacy & Security
    w_e2c6b601 = LabelWidget(
        widget_id="e2c6b601-de48-4000-ad0b-b108fff790bb",
        label="Privacy & Security",
        visible=True,
        enabled=True,
    )
    w_95bf8922.add_child(w_e2c6b601)
    # label: Checkbox: Allow anonymous usage analytics
    w_8e4d5eaa = LabelWidget(
        widget_id="8e4d5eaa-927e-4c02-bea7-91e97860543a",
        label="Checkbox: Allow anonymous usage analytics",
        visible=True,
        enabled=True,
    )
    w_95bf8922.add_child(w_8e4d5eaa)
    # label: Checkbox: Crash reporting
    w_412a197e = LabelWidget(
        widget_id="412a197e-58c3-4755-9567-0f7ea2dedcdf",
        label="Checkbox: Crash reporting",
        visible=True,
        enabled=True,
    )
    w_95bf8922.add_child(w_412a197e)
    # label: Checkbox: Auto-update
    w_5fa1f271 = LabelWidget(
        widget_id="5fa1f271-04a6-4af9-a22b-9dabe0c300a4",
        label="Checkbox: Auto-update",
        visible=True,
        enabled=True,
    )
    w_95bf8922.add_child(w_5fa1f271)
    # panel: e55bfbfd
    w_e55bfbfd = PanelWidget(
        widget_id="e55bfbfd-faba-46d2-969b-277beec1dd0f",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_dcfc1d9d.add_child(w_e55bfbfd)
    # Children of w_e55bfbfd
    # label: Notifications
    w_c8d572b2 = LabelWidget(
        widget_id="c8d572b2-cae7-4c52-bdad-cccdd94717e9",
        label="Notifications",
        visible=True,
        enabled=True,
    )
    w_e55bfbfd.add_child(w_c8d572b2)
    # label: Checkbox: Email notifications
    w_967d9d1d = LabelWidget(
        widget_id="967d9d1d-fedc-46c4-be64-ee21f2ab8801",
        label="Checkbox: Email notifications",
        visible=True,
        enabled=True,
    )
    w_e55bfbfd.add_child(w_967d9d1d)
    # label: Checkbox: Push notifications
    w_6fd28b94 = LabelWidget(
        widget_id="6fd28b94-b09e-4483-b396-8f6d73d4b3f9",
        label="Checkbox: Push notifications",
        visible=True,
        enabled=True,
    )
    w_e55bfbfd.add_child(w_6fd28b94)
    # label: Select: Frequency
    w_d7b79fc9 = LabelWidget(
        widget_id="d7b79fc9-36ba-48ba-b959-1cbd9b798b69",
        label="Select: Frequency",
        visible=True,
        enabled=True,
    )
    w_e55bfbfd.add_child(w_d7b79fc9)
    # panel: 41ae679a
    w_41ae679a = PanelWidget(
        widget_id="41ae679a-cb1e-494e-9c3d-fa64aebb2a95",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_dcfc1d9d.add_child(w_41ae679a)
    # Children of w_41ae679a
    # button: Cancel
    w_ac56e100 = ButtonWidget(
        widget_id="ac56e100-a20e-4765-a9ef-775d54cb7194",
        label="Cancel",
        visible=True,
        enabled=True,
        metadata={"variant": "secondary"},
    )
    w_41ae679a.add_child(w_ac56e100)
    # Event handlers for w_ac56e100
    w_ac56e100.on("click", lambda d, a="jaya:close_dialog", p={}: jaya_dispatch(a, p))
    # button: Save Changes
    w_76403ade = ButtonWidget(
        widget_id="76403ade-aa3f-4b8a-9fe2-ec51d7b1ef6d",
        label="Save Changes",
        visible=True,
        enabled=True,
        metadata={"variant": "primary"},
    )
    w_41ae679a.add_child(w_76403ade)
    # Event handlers for w_76403ade
    w_76403ade.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.
    
    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict
        
    Returns:
        Result dict with status and any output data
    """
    config = config or {}
    
    # Build scene
    root = build_scene_b38e87e4()
    
    # Initialize runtime
    from jaya_core.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="b38e87e4",
        feature_name="settings_dialog",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )
    
    # Set global runtime reference for dispatch
    set_runtime(runtime)
    
    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))
    
    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "settings_dialog"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

def feature_manifest() -> Dict[str, Any]:
    """Return the generated feature's registration contract."""
    return {
        "name": FEATURE_NAME,
        "id": FEATURE_ID,
        "version": FEATURE_VERSION,
        "description": FEATURE_DESCRIPTION,
        "protocol_version": FEATURE_PROTOCOL_VERSION,
        "entry_point": "run_feature",
        "capabilities": ["ui", "events", "state", "jaya_actions"],
        "permissions": ["ui_mount", "state_read", "state_write", "api_call"],
    }

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.
    
    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action
        
    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}
    
    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        print(f"Warning: No JAYA bridge set, action {action} dropped")
        return None
    
    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as e:
        print(f"JAYA dispatch error: {e}")
        return None

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
