"""
JAYA Dynamic Feature: Settings
Generated by FeatureCompiler v0.1
Feature ID: a2e27860
Description: Application settings and preferences

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "settings_dialog"
FEATURE_ID = "a2e27860"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Application settings and preferences"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from jaya_core.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from jaya_core.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class TextInputWidget(WidgetBase):
    """Text Input widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="text_input", **kwargs)
        self._value = kwargs.get('value', '')
        self.placeholder = kwargs.get('placeholder', '')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_value":
            self._value = payload.get("value", "")
            self.emit("change", {"value": self._value})
            return {"value": self._value}
        elif action == "get_value":
            return {"value": self._value}
        elif action == "focus":
            self.emit("focus", {})
            return {"focused": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_a2e27860() -> WidgetBase:
    """Build the "Settings" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="a4f33e9e-441b-4dd9-9586-2fa989e2610c",
        label="Untitled",
        layout="flex_col",
        rect={"x": {"value": 0, "unit": "px"}, "y": {"value": 0, "unit": "px"}, "width": {"value": 600.0, "unit": "px"}, "height": {"value": 700.0, "unit": "px"}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: 0ff75e2f
    w_0ff75e2f = PanelWidget(
        widget_id="0ff75e2f-037f-47ad-9c2b-76f0090c0207",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_0ff75e2f)
    # Children of w_0ff75e2f
    # label: Untitled
    w_29ac4681 = LabelWidget(
        widget_id="29ac4681-7d9b-424f-8524-0c06e3db1f95",
        label="Untitled",
        visible=True,
        enabled=True,
    )
    w_0ff75e2f.add_child(w_29ac4681)
    # panel: 1fcb35e9
    w_1fcb35e9 = PanelWidget(
        widget_id="1fcb35e9-69e5-4cdd-9fcb-edfc02d2ade8",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_0ff75e2f.add_child(w_1fcb35e9)
    # Children of w_1fcb35e9
    # label: General
    w_72acd16b = LabelWidget(
        widget_id="72acd16b-4bf2-42d9-9fc5-775439d9e889",
        label="General",
        visible=True,
        enabled=True,
    )
    w_1fcb35e9.add_child(w_72acd16b)
    # text_input: 30adac81
    w_30adac81 = TextInputWidget(
        widget_id="30adac81-fcd5-4dec-9757-dfe879ed8e12",
        label="",
        visible=True,
        enabled=True,
        value="",
        placeholder="Your name",
    )
    w_1fcb35e9.add_child(w_30adac81)
    # label: Select: Language
    w_2c6070ae = LabelWidget(
        widget_id="2c6070ae-6492-4663-9f3e-83b12b5813f4",
        label="Select: Language",
        visible=True,
        enabled=True,
    )
    w_1fcb35e9.add_child(w_2c6070ae)
    # label: Select: Theme
    w_d4a9256b = LabelWidget(
        widget_id="d4a9256b-7097-4321-978d-e591c2214aba",
        label="Select: Theme",
        visible=True,
        enabled=True,
    )
    w_1fcb35e9.add_child(w_d4a9256b)
    # panel: ee06502a
    w_ee06502a = PanelWidget(
        widget_id="ee06502a-06b7-4317-80e7-8bdf27efa63f",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_0ff75e2f.add_child(w_ee06502a)
    # Children of w_ee06502a
    # label: Privacy & Security
    w_9dd0fcc7 = LabelWidget(
        widget_id="9dd0fcc7-55b8-42db-a0ef-0f428f2234c3",
        label="Privacy & Security",
        visible=True,
        enabled=True,
    )
    w_ee06502a.add_child(w_9dd0fcc7)
    # label: Checkbox: Allow anonymous usage analytics
    w_aada2440 = LabelWidget(
        widget_id="aada2440-001a-474f-b239-ee28629d39f3",
        label="Checkbox: Allow anonymous usage analytics",
        visible=True,
        enabled=True,
    )
    w_ee06502a.add_child(w_aada2440)
    # label: Checkbox: Crash reporting
    w_2f81814a = LabelWidget(
        widget_id="2f81814a-d74d-45f6-9c2b-19f96e4ec9db",
        label="Checkbox: Crash reporting",
        visible=True,
        enabled=True,
    )
    w_ee06502a.add_child(w_2f81814a)
    # label: Checkbox: Auto-update
    w_94b07424 = LabelWidget(
        widget_id="94b07424-4ba0-4364-bf9d-89fba94ddc14",
        label="Checkbox: Auto-update",
        visible=True,
        enabled=True,
    )
    w_ee06502a.add_child(w_94b07424)
    # panel: 006d5bfe
    w_006d5bfe = PanelWidget(
        widget_id="006d5bfe-da05-4d11-9664-b4cd8c3e693f",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_0ff75e2f.add_child(w_006d5bfe)
    # Children of w_006d5bfe
    # label: Notifications
    w_52a50533 = LabelWidget(
        widget_id="52a50533-fbb9-41d9-bc1b-e5d3112e980a",
        label="Notifications",
        visible=True,
        enabled=True,
    )
    w_006d5bfe.add_child(w_52a50533)
    # label: Checkbox: Email notifications
    w_7c825936 = LabelWidget(
        widget_id="7c825936-40ae-415d-99c4-2d54dadbf12e",
        label="Checkbox: Email notifications",
        visible=True,
        enabled=True,
    )
    w_006d5bfe.add_child(w_7c825936)
    # label: Checkbox: Push notifications
    w_d9c77ecc = LabelWidget(
        widget_id="d9c77ecc-1e52-408f-b094-e131d52ca4a3",
        label="Checkbox: Push notifications",
        visible=True,
        enabled=True,
    )
    w_006d5bfe.add_child(w_d9c77ecc)
    # label: Select: Frequency
    w_f575f9c3 = LabelWidget(
        widget_id="f575f9c3-c006-4545-aea7-45f13ff84251",
        label="Select: Frequency",
        visible=True,
        enabled=True,
    )
    w_006d5bfe.add_child(w_f575f9c3)
    # panel: 678bfd70
    w_678bfd70 = PanelWidget(
        widget_id="678bfd70-f87e-4e67-acc9-85c423463432",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_0ff75e2f.add_child(w_678bfd70)
    # Children of w_678bfd70
    # button: Cancel
    w_83ef023a = ButtonWidget(
        widget_id="83ef023a-ee1f-4172-ba2b-6c406fc6ef29",
        label="Cancel",
        visible=True,
        enabled=True,
        metadata={"variant": "secondary"},
    )
    w_678bfd70.add_child(w_83ef023a)
    # Event handlers for w_83ef023a
    w_83ef023a.on("click", lambda d, a="jaya:close_dialog", p={}: jaya_dispatch(a, p))
    # button: Save Changes
    w_7d46bcb7 = ButtonWidget(
        widget_id="7d46bcb7-8848-47e7-8d2c-04b7b422d5ad",
        label="Save Changes",
        visible=True,
        enabled=True,
        metadata={"variant": "primary"},
    )
    w_678bfd70.add_child(w_7d46bcb7)
    # Event handlers for w_7d46bcb7
    w_7d46bcb7.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.

    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict

    Returns:
        Result dict with status and any output data
    """
    config = config or {}

    # Build scene
    root = build_scene_a2e27860()

    # Initialize runtime
    from jaya_core.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="a2e27860",
        feature_name="settings_dialog",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )

    # Set global runtime reference for dispatch
    set_runtime(runtime)

    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))

    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "settings_dialog"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.

    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action

    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}

    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        print(f"Warning: No JAYA bridge set, action {action} dropped")
        return None

    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as e:
        print(f"JAYA dispatch error: {e}")
        return None

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
