"""
JAYA Dynamic Feature: Dashboard
Generated by FeatureCompiler v0.1
Feature ID: bbac3d21-94d5-469c-9ec7-fd30b27c481c
Description: Main dashboard with metrics and quick actions

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "dashboard"
FEATURE_ID = "bbac3d21-94d5-469c-9ec7-fd30b27c481c"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """Main dashboard with metrics and quick actions"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from src.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from src.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_bbac3d21() -> WidgetBase:
    """Build the "Dashboard" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="ebc08769-441c-44c7-bf1b-148b47612983",
        label="Untitled",
        layout="flex_col",
        rect={'x': {'value': 0, 'unit': 'px'}, 'y': {'value': 0, 'unit': 'px'}, 'width': {'value': 1200.0, 'unit': 'px'}, 'height': {'value': 800.0, 'unit': 'px'}},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: 887682ba
    w_887682ba = PanelWidget(
        widget_id="887682ba-ab1b-47bf-b4d9-0be72389d3ff",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    root.add_child(w_887682ba)
    # Children of w_887682ba
    # label: Untitled
    w_24aa87c7 = LabelWidget(
        widget_id="24aa87c7-fb9f-4cb8-ab87-61652333a85d",
        label="Untitled",
        visible=True,
        enabled=True,
    )
    w_887682ba.add_child(w_24aa87c7)
    # panel: 5b889b2a
    w_5b889b2a = PanelWidget(
        widget_id="5b889b2a-b6b9-478e-b773-9749914abb49",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_887682ba.add_child(w_5b889b2a)
    # Children of w_5b889b2a
    # button: New Task
    w_d762ffce = ButtonWidget(
        widget_id="d762ffce-cd4b-4458-b9ba-ad2a84e8a079",
        label="New Task",
        visible=True,
        enabled=True,
        metadata={'variant': 'primary'},
    )
    w_5b889b2a.add_child(w_d762ffce)
    # Event handlers for w_d762ffce
    w_d762ffce.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))
    # button: Settings
    w_7d3c612e = ButtonWidget(
        widget_id="7d3c612e-dffb-42a4-8746-c67f154f9a47",
        label="Settings",
        visible=True,
        enabled=True,
        metadata={'variant': 'secondary'},
    )
    w_5b889b2a.add_child(w_7d3c612e)
    # Event handlers for w_7d3c612e
    w_7d3c612e.on("click", lambda d, a="jaya:open_dialog", p={}: jaya_dispatch(a, p))
    # panel: 37ae6cc8
    w_37ae6cc8 = PanelWidget(
        widget_id="37ae6cc8-b906-4e91-9b83-dde727e23dd2",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_37ae6cc8)
    # Children of w_37ae6cc8
    # panel: 9e6dc353
    w_9e6dc353 = PanelWidget(
        widget_id="9e6dc353-6277-4e81-8d87-4964e62ef9be",
        label="",
        layout="flex_row",
        visible=True,
        enabled=True,
    )
    w_37ae6cc8.add_child(w_9e6dc353)
    # Children of w_9e6dc353
    # panel: 86be7c65
    w_86be7c65 = PanelWidget(
        widget_id="86be7c65-940c-4c7e-8618-fac3beba9115",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_9e6dc353.add_child(w_86be7c65)
    # Children of w_86be7c65
    # label: Total Tasks
    w_25457b8f = LabelWidget(
        widget_id="25457b8f-519a-476c-b60b-648c0488042b",
        label="Total Tasks",
        visible=True,
        enabled=True,
    )
    w_86be7c65.add_child(w_25457b8f)
    # label: 1,234
    w_c6e71cef = LabelWidget(
        widget_id="c6e71cef-1b55-42de-a3c1-08e63237ed4e",
        label="1,234",
        visible=True,
        enabled=True,
    )
    w_86be7c65.add_child(w_c6e71cef)
    # label: +12%
    w_589e92ac = LabelWidget(
        widget_id="589e92ac-5c7f-470a-8c22-65d0669eb8a7",
        label="+12%",
        visible=True,
        enabled=True,
    )
    w_86be7c65.add_child(w_589e92ac)
    # panel: 807712b1
    w_807712b1 = PanelWidget(
        widget_id="807712b1-36ef-45e5-94a1-9d48597e4726",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_9e6dc353.add_child(w_807712b1)
    # Children of w_807712b1
    # label: Completed
    w_f56bb976 = LabelWidget(
        widget_id="f56bb976-f50f-46f8-8f35-346851d38ebb",
        label="Completed",
        visible=True,
        enabled=True,
    )
    w_807712b1.add_child(w_f56bb976)
    # label: 987
    w_8cff8415 = LabelWidget(
        widget_id="8cff8415-cbec-46ac-99e7-c6c6aa1a8cd6",
        label="987",
        visible=True,
        enabled=True,
    )
    w_807712b1.add_child(w_8cff8415)
    # label: +8%
    w_e28e28f8 = LabelWidget(
        widget_id="e28e28f8-40d1-4ad3-b866-33ecf0214672",
        label="+8%",
        visible=True,
        enabled=True,
    )
    w_807712b1.add_child(w_e28e28f8)
    # panel: 2e406063
    w_2e406063 = PanelWidget(
        widget_id="2e406063-7e03-49c1-a322-6f2d907f7c13",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_9e6dc353.add_child(w_2e406063)
    # Children of w_2e406063
    # label: In Progress
    w_a23595a4 = LabelWidget(
        widget_id="a23595a4-66b3-4fbd-b702-6e07c15cb767",
        label="In Progress",
        visible=True,
        enabled=True,
    )
    w_2e406063.add_child(w_a23595a4)
    # label: 156
    w_0c8f432d = LabelWidget(
        widget_id="0c8f432d-cf56-4bf5-b37f-2bee397b74bc",
        label="156",
        visible=True,
        enabled=True,
    )
    w_2e406063.add_child(w_0c8f432d)
    # label: -3%
    w_a344a68d = LabelWidget(
        widget_id="a344a68d-bd19-47a3-ac91-a84568f880a9",
        label="-3%",
        visible=True,
        enabled=True,
    )
    w_2e406063.add_child(w_a344a68d)
    # panel: 623e605e
    w_623e605e = PanelWidget(
        widget_id="623e605e-37e1-44a1-98c9-949ecef37d17",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    w_9e6dc353.add_child(w_623e605e)
    # Children of w_623e605e
    # label: Overdue
    w_5af49a2d = LabelWidget(
        widget_id="5af49a2d-c615-46cd-8e63-883b9bd5c939",
        label="Overdue",
        visible=True,
        enabled=True,
    )
    w_623e605e.add_child(w_5af49a2d)
    # label: 12
    w_710fb154 = LabelWidget(
        widget_id="710fb154-9f3d-4fc9-86a8-dfdae455aa15",
        label="12",
        visible=True,
        enabled=True,
    )
    w_623e605e.add_child(w_710fb154)
    # label: +2%
    w_76411e1d = LabelWidget(
        widget_id="76411e1d-c3f1-404e-bf5f-3c09c9cd5ab6",
        label="+2%",
        visible=True,
        enabled=True,
    )
    w_623e605e.add_child(w_76411e1d)

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.

    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict

    Returns:
        Result dict with status and any output data
    """
    config = config or {}

    # Build scene
    root = build_scene_bbac3d21()

    # Initialize runtime
    from src.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="bbac3d21-94d5-469c-9ec7-fd30b27c481c",
        feature_name="dashboard",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )

    # Set global runtime reference for dispatch
    set_runtime(runtime)

    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))

    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "dashboard"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

def feature_manifest() -> Dict[str, Any]:
    """Return the generated feature's registration contract."""
    return {
        "name": FEATURE_NAME,
        "id": FEATURE_ID,
        "version": FEATURE_VERSION,
        "description": FEATURE_DESCRIPTION,
        "protocol_version": FEATURE_PROTOCOL_VERSION,
        "entry_point": "run_feature",
        "capabilities": ["ui", "events", "state", "jaya_actions"],
        "permissions": ["ui_mount", "state_read", "state_write", "api_call"],
    }

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.

    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action

    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}

    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        return {
            "success": False,
            "error_code": "BRIDGE_UNAVAILABLE",
            "action": action,
        }

    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as exc:
        return {
            "success": False,
            "error_code": "BRIDGE_DISPATCH_FAILED",
            "action": action,
            "error_type": type(exc).__name__,
        }

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
