"""
JAYA Dynamic Feature: Login Dialog
Generated by FeatureCompiler v0.1
Feature ID: aa969568
Description: User authentication dialog

This module is auto-generated. Do not edit directly.
To modify the UI, update the SceneGraph and recompile.
"""

# Feature metadata
FEATURE_NAME = "login_dialog"
FEATURE_ID = "aa969568-6131-4d7a-b4fc-d60ca4ebbf6a"
FEATURE_VERSION = "0.1.0"
FEATURE_DESCRIPTION = """User authentication dialog"""

# JAYA Feature Protocol
FEATURE_PROTOCOL_VERSION = "1.0"


import asyncio
import json
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Set
from abc import ABC, abstractmethod

# JAYA runtime imports
try:
    from src.os_kernel.feature_runtime import FeatureRuntime, WidgetBase, EventBus
    from src.os_kernel.feature_bridge import JayaBridge
except ImportError:
    # Fallback for standalone testing
    FeatureRuntime = object
    WidgetBase = object
    EventBus = object
    JayaBridge = object

# Design System Tokens
STYLE_TOKENS = {
    "--jaya-color-primary": "#0066CC",
    "--jaya-color-secondary": "#6C757D",
    "--jaya-color-success": "#28A745",
    "--jaya-color-warning": "#FFC107",
    "--jaya-color-danger": "#DC3545",
    "--jaya-color-background": "#FFFFFF",
    "--jaya-color-surface": "#F8F9FA",
    "--jaya-color-text": "#212529",
    "--jaya-color-text-muted": "#6C757D",
    "--jaya-color-border": "#DEE2E6",
    "--jaya-spacing-xs": "4px",
    "--jaya-spacing-sm": "8px",
    "--jaya-spacing-md": "16px",
    "--jaya-spacing-lg": "24px",
    "--jaya-spacing-xl": "32px",
    "--jaya-font-family": "system-ui, -apple-system, sans-serif",
    "--jaya-font-size-sm": "12px",
    "--jaya-font-size-md": "14px",
    "--jaya-font-size-lg": "18px",
    "--jaya-font-size-xl": "24px",
    "--jaya-font-weight-normal": "400",
    "--jaya-font-weight-medium": "500",
    "--jaya-font-weight-bold": "700",
    "--jaya-border-radius-sm": "4px",
    "--jaya-border-radius-md": "8px",
    "--jaya-border-radius-lg": "12px",
    "--jaya-border-width": "1px",
    "--jaya-shadow-sm": "0 1px 2px rgba(0,0,0,0.05)",
    "--jaya-shadow-md": "0 4px 6px rgba(0,0,0,0.1)",
    "--jaya-shadow-lg": "0 10px 15px rgba(0,0,0,0.1)",
    "--jaya-transition-fast": "150ms ease",
    "--jaya-transition-normal": "250ms ease",
    "--jaya-transition-slow": "350ms ease",
}

def get_token(name: str, default: str = "") -> str:
    """Get a design token value."""
    return STYLE_TOKENS.get(name, default)


# Base Widget Class

class WidgetBase:
    """Base class for all JAYA widgets."""

    def __init__(
        self,
        widget_id: str,
        widget_type: str,
        label: str = "",
        style: Dict[str, str] = None,
        layout: str = None,
        rect: Dict = None,
        visible: bool = True,
        enabled: bool = True,
        metadata: Dict = None,
    ):
        self.widget_id = widget_id
        self.widget_type = widget_type
        self.label = label
        self.style = style or {}
        self.layout = layout
        self.rect = rect
        self.visible = visible
        self.enabled = enabled
        self.metadata = metadata or {}
        self.children: List[WidgetBase] = []
        self.event_handlers: Dict[str, List[Callable]] = {}
        self.bindings: List[Dict] = {}
        self._state: Dict[str, Any] = {}
        self._parent: Optional[WidgetBase] = None

    def add_child(self, child: "WidgetBase") -> "WidgetBase":
        child._parent = self
        self.children.append(child)
        return child

    def remove_child(self, child: "WidgetBase") -> bool:
        if child in self.children:
            child._parent = None
            self.children.remove(child)
            return True
        return False

    def on(self, event: str, handler: Callable) -> None:
        if event not in self.event_handlers:
            self.event_handlers[event] = []
        self.event_handlers[event].append(handler)

    def emit(self, event: str, data: Any = None) -> None:
        if event in self.event_handlers:
            for handler in self.event_handlers[event]:
                try:
                    handler(data)
                except Exception as e:
                    print(f"Event handler error: {e}")

    def set_state(self, key: str, value: Any) -> None:
        self._state[key] = value
        self.emit("state_change", {{"key": key, "value": value}})

    def get_state(self, key: str, default: Any = None) -> Any:
        return self._state.get(key, default)

    def apply_bindings(self, global_state: Dict[str, Any]) -> None:
        """Apply data bindings from global state."""
        for binding in self.bindings:
            source_path = binding.get("source", "")
            target = binding.get("target", "")
            transform = binding.get("transform")
            fallback = binding.get("fallback")

            # Resolve source path (e.g., "state.user.name")
            value = self._resolve_path(global_state, source_path)
            if value is None:
                value = fallback

            # Apply transform
            if transform == "uppercase" and isinstance(value, str):
                value = value.upper()
            elif transform == "lowercase" and isinstance(value, str):
                value = value.lower()
            elif transform == "json":
                value = json.dumps(value)
            elif transform == "date" and hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d")

            # Apply to target property
            if target == "text":
                self.label = str(value)
            elif target == "value":
                self._value = value
            elif target == "visible":
                self.visible = bool(value)
            elif target == "enabled":
                self.enabled = bool(value)
            elif hasattr(self, target):
                setattr(self, target, value)

    def _resolve_path(self, obj: Dict, path: str) -> Any:
        """Resolve a dot-notation path in a nested dict."""
        parts = path.split(".")
        current = obj
        for part in parts:
            if isinstance(current, dict) and part in current:
                current = current[part]
            else:
                return None
        return current

    def render(self) -> Dict[str, Any]:
        """Render widget to serializable dict for transport."""
        return {{
            "id": self.widget_id,
            "type": self.widget_type,
            "label": self.label,
            "style": self.style,
            "layout": self.layout,
            "rect": self.rect,
            "visible": self.visible,
            "enabled": self.enabled,
            "metadata": self.metadata,
            "children": [c.render() for c in self.children],
            "state": self._state,
        }}

    @abstractmethod
    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle a JAYA action dispatched to this widget."""
        pass




# Widget Implementations

class ButtonWidget(WidgetBase):
    """Button widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="button", **kwargs)
        self._value = kwargs.get('value', False)

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "click":
            self._value = not self._value
            self.emit("click", {"value": self._value})
            return {"clicked": True, "value": self._value}
        return None

    


class LabelWidget(WidgetBase):
    """Label widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="label", **kwargs)
        pass

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_text":
            self.label = payload.get("text", "")
            return {"text": self.label}
        return None

    


class PanelWidget(WidgetBase):
    """Panel widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="panel", **kwargs)
        self.layout = kwargs.get('layout', 'flex_col')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "add_child":
            # Child addition handled at runtime
            return {"added": True}
        elif action == "remove_child":
            return {"removed": True}
        return None

    


class TextInputWidget(WidgetBase):
    """Text Input widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="text_input", **kwargs)
        self._value = kwargs.get('value', '')
        self.placeholder = kwargs.get('placeholder', '')

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "set_value":
            self._value = payload.get("value", "")
            self.emit("change", {"value": self._value})
            return {"value": self._value}
        elif action == "get_value":
            return {"value": self._value}
        elif action == "focus":
            self.emit("focus", {})
            return {"focused": True}
        return None

    


class WindowWidget(WidgetBase):
    """Window widget implementation."""

    def __init__(self, **kwargs):
        super().__init__(widget_type="window", **kwargs)
        self.title = kwargs.get('label', 'Window')
        self.minimized = False
        self.maximized = False

    def handle_action(self, action: str, payload: Dict) -> Any:
        """Handle JAYA actions specific to this widget type."""
        if action == "minimize":
            self.minimized = True
            return {"minimized": True}
        elif action == "maximize":
            self.maximized = not self.maximized
            return {"maximized": self.maximized}
        elif action == "close":
            self.emit("close", {})
            return {"closed": True}
        elif action == "set_title":
            self.title = payload.get("title", "")
            return {"title": self.title}
        return None

    


def build_scene_aa969568() -> WidgetBase:
    """Build the "Login Dialog" scene graph."""
    # Global state
    global_state = {}

    # Create root widget
    root = WindowWidget(
        widget_id="3accc7dc-a9bc-4fcd-a552-922b1f8ef719",
        label="Untitled",
        layout="flex_col",
        rect={"x": {"value": 0, "unit": "px"}, "y": {"value": 0, "unit": "px"}, "width": null, "height": null},
        visible=True,
        enabled=True,
    )

    # Build child hierarchy
    # panel: 90fb187f
    w_90fb187f = PanelWidget(
        widget_id="90fb187f-ae9b-46a9-a390-3a1a3577311d",
        label="",
        layout="flex_col",
        visible=True,
        enabled=True,
    )
    root.add_child(w_90fb187f)
    # Children of w_90fb187f
    # label: Welcome to JAYA
    w_2f663928 = LabelWidget(
        widget_id="2f663928-c7c4-4b63-bbbe-14602e1c95bd",
        label="Welcome to JAYA",
        visible=True,
        enabled=True,
    )
    w_90fb187f.add_child(w_2f663928)
    # text_input: d807b0fd
    w_d807b0fd = TextInputWidget(
        widget_id="d807b0fd-6ccc-4773-8844-6ab12ddd2f5b",
        label="",
        visible=True,
        enabled=True,
        value="",
        placeholder="Username or Email",
    )
    w_90fb187f.add_child(w_d807b0fd)
    # Event handlers for w_d807b0fd
    w_d807b0fd.on("change", lambda d, a="jaya:update_state", p={}: jaya_dispatch(a, p))
    # text_input: ef234f83
    w_ef234f83 = TextInputWidget(
        widget_id="ef234f83-a926-4072-aa47-d16a8051a4a4",
        label="",
        visible=True,
        enabled=True,
        value="",
        placeholder="Password",
    )
    w_90fb187f.add_child(w_ef234f83)
    # Event handlers for w_ef234f83
    w_ef234f83.on("change", lambda d, a="jaya:update_state", p={}: jaya_dispatch(a, p))
    # button: Sign In
    w_4c48a402 = ButtonWidget(
        widget_id="4c48a402-72f0-40c6-b2f0-70290583dd39",
        label="Sign In",
        visible=True,
        enabled=True,
        metadata={"variant": "primary"},
    )
    w_90fb187f.add_child(w_4c48a402)
    # Event handlers for w_4c48a402
    w_4c48a402.on("click", lambda d, a="jaya:run_task", p={}: jaya_dispatch(a, p))

    # Apply global bindings
    def apply_all_bindings(widget):
        widget.apply_bindings(global_state)
        for child in widget.children:
            apply_all_bindings(child)
    apply_all_bindings(root)

    return root

# Feature Entry Point
async def run_feature(jaya_bridge: JayaBridge, config: Dict = None) -> Dict[str, Any]:
    """Main entry point for the feature.
    
    Args:
        jaya_bridge: Bridge to JAYA core for actions/events
        config: Optional configuration dict
        
    Returns:
        Result dict with status and any output data
    """
    config = config or {}
    
    # Build scene
    root = build_scene_aa969568()
    
    # Initialize runtime
    from src.os_kernel.feature_runtime import FeatureRuntime, EventBus
    event_bus = EventBus()
    runtime = FeatureRuntime(
        feature_id="aa969568",
        feature_name="login_dialog",
        mount_point=config.get("mount_point", "body"),
        root_widget=root,
        event_bus=event_bus,
    )
    
    # Set global runtime reference for dispatch
    set_runtime(runtime)
    
    # Mount feature
    await runtime.mount(root, config.get("mount_point", "body"))
    
    # Run feature lifecycle
    try:
        await runtime.run()
        return {"status": "completed", "feature": "login_dialog"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
    finally:
        await runtime.unmount()

def feature_manifest() -> Dict[str, Any]:
    """Return the generated feature's registration contract."""
    return {
        "name": FEATURE_NAME,
        "id": FEATURE_ID,
        "version": FEATURE_VERSION,
        "description": FEATURE_DESCRIPTION,
        "protocol_version": FEATURE_PROTOCOL_VERSION,
        "entry_point": "run_feature",
        "capabilities": ["ui", "events", "state", "jaya_actions"],
        "permissions": ["ui_mount", "state_read", "state_write", "api_call"],
    }

_runtime: Optional[FeatureRuntime] = None

def set_runtime(runtime: FeatureRuntime) -> None:
    """Set the global runtime reference for dispatch."""
    global _runtime
    _runtime = runtime

def dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch an action to the feature's widget tree.
    
    Args:
        action: Action identifier (e.g., "click", "get_children", "set_value")
        payload: Optional payload for the action
        
    Returns:
        Result from the widget that handled the action
    """
    if _runtime is None:
        return {"error": "Feature not running"}
    
    return _runtime.dispatch(action, payload or {})


# JAYA Action Dispatcher
_jaya_bridge: Optional[JayaBridge] = None

def set_jaya_bridge(bridge: JayaBridge) -> None:
    """Set the JAYA bridge for action dispatch."""
    global _jaya_bridge
    _jaya_bridge = bridge

async def jaya_dispatch(action: str, payload: Dict = None) -> Any:
    """Dispatch a JAYA action through the bridge."""
    if _jaya_bridge is None:
        print(f"Warning: No JAYA bridge set, action {action} dropped")
        return None
    
    try:
        return await _jaya_bridge.dispatch(action, payload or {})
    except Exception as e:
        print(f"JAYA dispatch error: {e}")
        return None

# Standard JAYA Actions
class JayaActions:
    """Standard action identifiers."""
    RUN_TASK = "jaya:run_task"
    OPEN_DIALOG = "jaya:open_dialog"
    CLOSE_DIALOG = "jaya:close_dialog"
    NAVIGATE = "jaya:navigate"
    NOTIFY = "jaya:notify"
    UPDATE_STATE = "jaya:update_state"
    CALL_API = "jaya:call_api"
    EXECUTE_CODE = "jaya:execute_code"
    SAVE_FILE = "jaya:save_file"
    LOAD_FILE = "jaya:load_file"
    OPEN_URL = "jaya:open_url"
    COPY_TO_CLIPBOARD = "jaya:copy_to_clipboard"
    FOCUS_WIDGET = "jaya:focus_widget"
    SCROLL_TO = "jaya:scroll_to"
